apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qBOeLlPebEeXIo44GSEEvfgtCqCQuJIJNwzqoVZv+6JASGqWKHOhsNLNh5Proi84wzxXd2aN19MC4oP7oRTwkqEwo8ab7T5rEqkahvUWMaghqDaamwBQ+Ex0Gmt4bkctgClR1Xa4lIHI/2Y+9W4JKUdi6OkvGe0ywqUNgCchhUXSwCh0I/LT+cDOW96rmCy4Y538/RRUpk6yKWabHRnKwj08d1LhcIJ2HwRJ++98IP9L/cMbUM93mB0P4WW6tCRiNgxFX2aXE2mSj3+EqUvrIY1p9CqkzGjTaHCFAaZJpUTWI2fLUKfTogb7a0uwdOJBnJYhPbNl2aBKY0VDzvc0ocGk8QiT8nkxLeCGHZfj49PZY4feUlsHUt7ZDzfoiKPW,iv:Zor6xNIGmGZ5JaRFsAySA3ie2zPClG9Eic2FHBcHHX0=,tag:RUTom0K+ctl2JsX1uNgEZA==,type:str]
    identity.pub: ENC[AES256_GCM,data:hhJc8OotTpKS7htygEgEshBKzfniTkCSM12nzCNknAqYbBpcCNIuWyCARW4qvHINUm95Kw+R0xOvVwuuQgEhPP5CyS1MzceRWf6AprAD+1v74IvcrrFNJfJJR/B9SK4GsXYxVSFOuvX0f4XvkbakWwpojOGJpDDY/UcGEBfE/LurhuHpEFB2UkBibY6mfwhCuCzuBn4C2tAKj1wNppD9dFDZq/LkyIq+3wxMsAtVSQKZR/gOFJmK+FpTDk5Til7V/6oi9dqWp8PUXBsyIA==,iv:5jAqIYv8Mc3DfGpmPUoE8qRuV0ifuOfGKurO07EGDRI=,tag:mebkTSAn16rVSh2p2kMqWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ciAntvx5xKauFpfgrIGgTewb/llLSeYrg6MasbW45oPuC9F3ZBUJAT7qL+ZBf0gbVclIkYfB+LpEYjri0r+dRUJ2R5/Dejz8yiXaevCH6Xpzsq+QYDhgbaNtSRRHaH9YGCbanKyIm4m3UkPBsXgWE8FanaWclcBAzBwYhyv/h/1DOFSwZXPYmihDbrTGTlMeI/n6oxOYFnbfDifDqo3wJ8ESdtsVpRsLtP9k,iv:9d4KuRcXfLpmzphpujONI8F+dA02eN/rRmljnobyLzU=,tag:JjEHGH9Fuh+eFx/Sa0apwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV2pmTXhEdittSUxwUnMy
            RFdGNU05VlFKelVuMW1yM1E0YlNyU01QZlhzCnBuY1JoYlNJVVRadVJtclpKSjlw
            OU4vVU9Fb3RIS1IvZ0VIeFJrNXJDejQKLS0tIEZvUkpJNzVQYjRNV3ZDZ2VPdGt1
            c0huR2tNMzJNVlJ4R3ltZTFyR0xtcFEKf3cLJWNN46WdNQ+a4bsRMZTuPs+cnLIn
            61CbiEnUAWczcD1H3KqoYGptCrP2uOsL5hbgpUDBMNYdua9tjB2bRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T00:45:35Z"
    mac: ENC[AES256_GCM,data:R1dodEnLLvKTla6+V3XLpNAZiM0d4pqM0VyjmwatA8y2J9qNSsxcIFT6O+ry+5ZUkPuxoFmQv0Xpso3GBDr+gmgERunfeOhP0D30mbeN+AmCG4zFMq8FKQoD/tOEuaLf9vQdKTjyGc2lH7HdQDCWJzJzJonscLGnVKkKdFBrg/Q=,iv:LvWWATbtbJt3KTMmkBugAIGllLXYupEQlv/neNs2IYk=,tag:h9Uo9PDz1w0tj/HHRPCLZQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
