apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ic0U4OXyxlNGn9bnLAERWOOBUbP7r98T10paxUJD77rdRN5+rNt+nl16tNe6XHHGevPMpCA3MP/L5y3hzfa/oMnQRqEmsSLpArXDv7llNIgjOTPwmg3KKSUijGG6cLyujLzKWaWV/swjzK3KzYWuovDA6KEic6uoBQUuNUC6U8cmWaMjA8EZJx6WyAloG51sc6vsajob2Nm8oMRL+nvqnkLbjgasflKH60Glu5pnqZcvXHJ2cIwaLuzUX18IRgr1ZIjZVPKYTU9dPiS0pDCrj/s88DzkpHVYYuntvyQGW1UN2JeZICvfgLpojWU3+0x0TyjmKPnLzYY3XtVB6U9kO423B7IeirahUYgf+wurNDodY3taQaP0C6Ih2yJuLR9V,iv:9Sbo43KvF/YTqLBdnkGhhnEj93cfcwnzxx6G8u2gb94=,tag:1T2FH9M2G34Cd8OAB1+MZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:iZFtHfSYuRtgFynh+HQWXZ2pedxXtx+yD8RN5Ulikco3wpHqTJbAiXagUd3/bYmJwWchRFbgLSF80lG4R+rlOaR03ITRFB+OcbguVLeF+9hGDqlzT2Z26J004LRMsodeHRcYYEWEK4w122t9dU1xIEHgos02liEGtpI+B5sD8biBSe8VL7rFE5SQN9w/RT0hIH+Q89jPcaaaZoEavp/oFdT+wqLEOwMPfT8jNa95Zxk/hWA49YNY7borQxxk0YIWbNkpWO01xARFJr3buQ==,iv:T25bMiYerXc+DyMG21Xd2vo8dgNXZLLTiD3Xk9TYx0U=,tag:mpG2jK5ONEhc4L5sGu/w6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:o9yd139Kpqcaw9gfRwB84TfWeJztez7e9TANQ/MkDyH/HCLliBp0cHeWejlvF1vWfaboFkwH0XpiTy9ExdBC9Smfoatfz4lKfRVCKEN9KV+TmhaCDLM1zsBLhhU3yXGV5wtF6ExPlqMlPMF/SnLgvLI5itOqjl0QAhieBwHHe3x8C8ci4Pjde2eJCktF4BSITlU4fDsWbk19TEllfFI6/0wj6YArgMFwEqZu,iv:aUlWE9mok56zf8iUcoInUcd4QI3poXxE+9Y7jFrB5GQ=,tag:QYCQRRWaiZrJrdXIZt9iHQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY3liL2xJR3FVdnByMEEw
            UkJOQzVOdkYzQnNrUXlWSTFaR2NBTmhhVjE4ClAyTENZTm5BS2JzUW13R3FxOUpw
            S0xiUERDTUpWb0lzOTAxOHI4dlZhUjgKLS0tIEJUMUtPVUgvV0ZKSWhYeUdudytt
            emhBVHRPbWVqZnJ2U0dQTFZ4WlozUHMKSExK1Mt8ae147Zv+5oevn+KsPYBZ7xMV
            ruulm/DGi3gwsYKe2xQHE7Ia1B6cYk63+QSCTze66OZj1K0Yngu+kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T16:16:59Z"
    mac: ENC[AES256_GCM,data:FL+L5UlFEMwdj2Jry/Q6gGOmgIjxYhEDYKvklQDqNRjzgMJsyC2t2nMmiOFA/dxfQ6+8r23+OBFYSHayObrq1fdO9bbSw88ZEc16Zi0ASatgNOQaDPzjwEl4iPS6BUWLEw6M7nZto7vJYyRYyqRmEenv9/WIJZct3vP9pdYzNcE=,iv:mOiCKM4WNhsLxIaEAHrZsNdM9Hfz8xAg7fiLjD8vxOg=,tag:blHUahd1Kc3KHgpBPgqavQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
