apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CLmwxYCeINPG9iC3PHhoLRuhe6rI6lFyqsKq+XZU2SlDCVg1HhTF+OwUZgsHKlyVJmb7GxkWqqozwOhtT6hGUvNMwhsbFDkrw0tyIYqX44yzV46dke6TPKlkOhrR9Ghk1HqnkEuHlk3wkPMEBAncxZHjs/ItieMSQnQmIk+cFqcJYk80Na5W2n2tN3gml1peJgSXc31Ol1x7b1KKVqj0tXvqRXcHJ3sEWuxi0rYLwO/B/pNnoko1UVad+2OylwLNl+9YEbaiAGcgqno8s/OWxocPCyoGWQRlr+d0610Lk1gVSankuS56N95Koiha9bloi9PfLT/NPnr35mpiMVkMdEf8DbcdK6aMHA9UeGknasFFxndN+UE0YRiHwZiDs1XF,iv:WWZ75aHANyWe3MtaW3HkJiwytDL2jaZBdF87qLJzHH4=,tag:UtPOrw6ITxicl6MfXat2qA==,type:str]
    identity.pub: ENC[AES256_GCM,data:qhF5TCaFAZb9vC54XFSeODCIlS0C0JdxDxZioP3XnNwcCoDqlZnUvqrX+jf9BiWVbEUCuwRdOEbsHyPKNyYlUBf+btDtKEc0+jwA/f7kLbuABw+wsJaz269ffgwoxdxmy1jqCPSbjqglK0gyvbZCtlqsLBH4FbkmWJ/6HTFv9vICLC6e4zb1plD6drGn8K6GLXQh3IUetYymcASGGa+vB+XeyU/4LBJsf3DNloglgzhJrWPIX8KLc7XTId6CPkD+vgBHR+7vBjPJQ8NSxA==,iv:Ue3p7SvfNzmdGdju0+rPFBhiudw1t5i+BDxmBd2Dsxw=,tag:36s7S/RMNluyZgT7RuKyaw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RNsf9cRS0CocN7cgrSNcLyTKIvDXFX1aUxxhJUlR+Wu2PvZ5kSmaeGAmlGCz6NzqgwI/nQZQg/nde9LEzoABMDLFz1EW2JIHsY/T4YNFK7XOiVLh43tc3kDVgBggSmqT0mrQMrKINQbwalsfKiKVD8wLBhdN1xkiTyeALhbm2z50xzy+mfyLGJDSFZUtOEkDFMk4EDgp0YkSdnGbiqQ9wUo+YqX03fmlWBr2,iv:FKfgXZtGBZKrJblVZHnej3dYLwSLutFqP8lMKGuUTdA=,tag:uDWJNrevsTAwPUrQdEvnkg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaUE5QWIyRlRXczlCS3lD
            STB4a09hR0hleXBDVUdSSlNFN0dCWThaWVYwCjJlb2FCWVdpbGlWd01SWEkybXBY
            RHRYNWNici9sbVlSQ0dQSnFSVFlDRTAKLS0tIDA3cWE4Qm1hbkc3WUVRN2xPdDVK
            TVRtUTF2cksxV1J3WGlnU3MyaXMvNFEKa2p7kqo1okl++TIy32mzudh7ozjaH4ZA
            WBbg2OhKviZuC9iTmw3pMAX5cGJTcKNUGwotfsLFwYfpFMx2ahAH2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T20:22:09Z"
    mac: ENC[AES256_GCM,data:fPH8Z7C99mYgx6VokZQcIfMpEFVVAXdCDnh2WJwHmrfiRNKE8bQfPWGcDamJC5vg5kCtz8XfBX1eOPE9TZ+H+GdPQ/AZcc7Ny9hZfO8QSO83eIJZp4mwevbXXpbHTDHLWOCwTUvsJyLCTux9jq21PDmvd+8Bc6wDDv8LT8ePHw4=,iv:xkdZoa3lBDPq43MwqmF5J1pa/zkqTQpkDUthjiUO7ws=,tag:AD4m0dzVl0CwJ7gB/9h4PQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
