apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yiksLoGb8/EQt3+NE28S0xmqWr1cw5CvtUkh98irIlWrhMDoctQSPNlf+JlDH14Yzm7IWc1g6ZC0PINiLVqdDjRfmiRXBSgQUTXFD/GtvGXyBLqCUuFXa8WYwlBs+mvVeMeArJ8toLZMCKB8RSij4e6SW42kW6vIDUE5gjdZyKURUKhfafwpal/I38KjfUT0tHQrolv0+XUwWQ4Qv6m5KpXFE+JtabOxXl4E6JlRe8X6hEVckcLx/MXA7pbcIlN0LgmNugKQrhN2svYt55p4jJlL1olfC9TCCJFpTWDDTC4zh/nV5/VWOn+JY/MtWKOc57u7SoF7Kggkxbq6DQi+xICuUwZOrQVXdBMEM8SeIGTVzfoI0mVCChkxv8W+k/hO,iv:2KaR6LoW0sH0C8wnNxL1CtKWBFXkXXxMbKqViEHbtQs=,tag:GaMADZ2jMHREHyMDl/DEQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:kRBhv1xdjxEuNPqpStPGh4Fv3Io+VH7ZoecVAjravIb60Ix19PnYiVr93u0K9Ik2PhNkc5HoRoHNZQt7dQUa5gkAaGSh+y9CcRZvln9SRl7P4xEzcDPc8Vg2W3pGsAGCKdE0uHXvU7QXvKQcwPuhUap/BKHJaTIjUv1Yxl+4g6urUVWCsUa539bXHkhXAHrsEhbJsimgMvS0yyxz7u8VHSgx4I95KE41K1dMc1WaU/AAeBg6XfIyEu/t6yXxrhXPb9iVOwwr1JlRVkrvjQ==,iv:yxdxuseUVwDDcxKnOnQSjxIveZpgdbfeKjLavU423cI=,tag:9FtW+ZYal+36zKbE38K2NQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:PZcFhDdFqYOGt5iF2rQlABovyezr/U0dD5pht6gQGcDVuAuysEMVVquDTTPUgWxQqaZDoxyMUrAYv6AlQIrBgBO96zBFAJStl8sv11ENHkfyE0XNIoqWPj9LVmeMB9rfsjUkIFBqRrPDNPq8jXN91fvFJCigr2YdOJnxAz75a2jqJjBMtDBBXOIgY3xefvG2mN/zxcyxizART69U48lyIWATeZYc/3HaAVIr,iv:nHVSpUMXDgR5Nd/CfQRt353jGRWzQ76EWH9AC/Mv/8E=,tag:cWemdAD3XJF0+T1vcpXAiQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbWNJcUZGS3JLNzNMMjB5
            TmNaaGJwK1ZDQmhGTGlXdnVSeDdJamhQekMwCm9hT29hU1FZQStPM1I4eEY3cVBx
            NEY5TWVOVDNlZzR0V2RLSjZIY0ZqQzQKLS0tIHNxQm93MFR2b3o2U05VUjJGKzly
            eWdNQlBNWTdpelUwaXdhL1hYNjFMNWMK9NcuTwM6AUB4t811OeOx5QgrvovXnkDh
            nANRLl5+cMtaHATcikL0ulD9NrETqwW5D57QrdjXCPL++NRCdQHfsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:26:43Z"
    mac: ENC[AES256_GCM,data:9nI7Qq7YOlwvs8pUCZUvQ9SJf5W3g6Ma2TEtXsJ79x4F18JrJwtaO+bhIkWUYEJXBc7kpSeXE2xv9kAX0oSqlk4U/RkpVE+qitCHJBXLUU7yX39BHLAsQOWq0wxtX7+V0lDPa1CDrfm70lalsnvv/krpxcPEiCe8e+AVaur6pwE=,iv:T/SbcxKZjtwFJyksIm9/uwZNahA5QjxTYATaQ+szjPQ=,tag:l27DdC6GcnjPhwngoDOjwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
