apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WbBx/43RRP128k2dLOdzO29ns+iXR24pn9Jo4dw0bMXWz+HRpQZ/jJLsvKsngH6BjHJW1ZC2X/wdWjgufjuZ9yOpUiiXMvTNTWdJ/0HFGI+Ljj5iL6tpQ/HWvx3Ug6y2ULPhlUQUBP7Ay9TRXFBZ9r77trsejl9sd0OXYp8I7zAIkghaYDNspRWQDMqL+rQvg6Az/rG1AMLAW66Q5t0y1SmBYI7hlz4oha0XhuY3XojpOBe47kQZbG+J6/2B6j8aOTcsn7eXfYQlM1C55Fd841joTY1V2nahu9uTFws7BDFbvxwDGXsfGh4Mw3TS70ZjDucBinKeGEKI1IoC5J24yToR4xdZPdX+D8OMRu9CSyploT/C8AwGWtzawf93t+3W,iv:+GWFhWgqp5BrYNi6px20CJzihqHYEweOyqG2yRJh52c=,tag:2KfqQuYTX4Bkd2NO/cuRTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:KJCTSqQK38wwD9Q9sk9FXnm+Ma0WRP39ELBSYtHVqRJq5oXAWaDd2YiOC+upZP+z707kesHuPj1CSGvh/RFgehAubW1tdYw3EEncdzCYBT8d94INyapf0qe1/UjGq7PqwIPYZtRbKEm48hLtZYEkL7QitGXeYH0CzmdIPHC4V/N6W2VyAKOIlJd0Tm2fU/62pzlmg2kLPHHmI0SIF35VutIWSl/XExt5CxsSy1iqZwRZH540nDpFL9Qj4khwa2K+1FX4HeDZ/8go3tDolg==,iv:KAADMNb5sHjrGNdu+Jq+YnjotZSiiURUKHin85qgapk=,tag:b5AHJuwfpVQf8px60cevgw==,type:str]
    known_hosts: ENC[AES256_GCM,data:pNj7kWkRObBiXu5AKIyzE05IfZ4UOnuiQM271C9glkN5XzTPc4EFn6QIsOV1goc2hcw6aB4/Bzfs96hZs9QVpeJ/faIgKZVL7fv1hIvSBMyyJYrGdf1klJOc5zfzntXqUj0RqcN+Z3f0NiWE9gJNNzH9E7MWuSyhU85XuOAljAqxZaFxOmG8WlnpQSGDS00sGgRKK4ouFY9DqQlKJGqtmFKyuw61cVHj1NcK,iv:XnIkUvnF4TZRIniDEFcsEKSGyaZQjTFyuCzwWF6xma0=,tag:YDnMdHxmnyspZv9l0DudhA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2xLNGpKS3hjakJ1T01j
            eXlxeTBBaWNKaHdXejdtQXFxbjR4L2paTHljCkp4MEx0NFJPRjcraURCeVl5dFE1
            ZURaVlRHd2pKYk1MOVB6VndlVHVDSXMKLS0tIGY5OEFoN2pDeFY2NTI2MEZHMzQz
            UTh2a241OGI5VWhnRVdqZEIwcFZvaDAKZIngThomILjgh+CPy2BnpXsTmKhsMwFv
            sy38cYLBWBrhZOSpqvBLu7UHfbzSFe8K1SxoXEkhcv2atxMFnqhPKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T21:23:37Z"
    mac: ENC[AES256_GCM,data:29PO/1qJcuz43BU4WgDvk1C4dMokEJl1ZVtiTczcNbqB24tec9JlDiEfkZaVhD2NrMH1S8h3M7v0YN3Hsd2bU3hxUKARq13CIWVwOSxSxKzvtgnhrHAIxzQYTFDv+EfwR4e9SdYxzvpkVrsjGiW2iu2wm8cbGDYrLPx/jlveAfQ=,iv:MwVgQ2B+O0pyFxvBLBQiywyPVyaM8M6bQrZoxKSk3Fw=,tag:/BmRfmdk03yh1/e3U29TxA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
