apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UZPvjtI+Z2Hs2lv+peLAjSlBEQXr35+CgicZOXPzMgA6pLy/IWHtl9JWZjUBPlQBWxJ2CovbssujVt78noA4m6Nb0GAHwaFOor/kPbZ/hxKYIcOSYsRKkpGHdcLEjegPu5/BpPevWJAboF+SzkWvFDQIq6IALVAQpPtkYF9jWxY8qXpl6tf/PAsNUbIuMSkaMCweSHhRMFoR0M171HdnHkpuUPp7gmjXhWwXpuwaGhluk7tmy9BOGPe4wv7YKsktL0FQjZN2PCfSoXkHycr2wKWmaXN5BZwmd9RD1vSo+GwhJHt/cdvFbuZzg1JBGSMlK3Y467cuE0bLhj0Bv4pNq5bP+aRHJGtkhc9Ar8GpvDHrsdwOsOFnwSDvD6mk1dmM,iv:nueRWCzrdUt314kZPe15FJoAEUXxbav2Zt7RXH2fKeg=,tag:7ow0pp0CnWU6rgkmRWN1Jg==,type:str]
    identity.pub: ENC[AES256_GCM,data:sLfYOe0zCXq2GU10ytdGfnCj+lHPmHwUFz/QSPFy+zTeGUMnqKe/13FEHLn6BES/vQjjHTEzWajhBuzvOVDjWMtZedystrABEg+H2GOdmfuXE/EHVUpgEw2sCOeglb+ueuObOY193J+o6/Bz+m8pswf5xgYCViNK3xO1fNBrGnvbL49Cn3V+RMv3w8//+bLd7/PHl+OXliOTUAyr50Cvp1NLheWL9pGzOEFcSuSMZagpzm1Y90jdXln6ZqGfeEHBje2jvLmmTDw1+tQ0Sw==,iv:FJHrPB1T3vT6tykWFgErioZC7cDAi0fRF8S4q0JKe0k=,tag:e9zH1ul6qcy1Qs8zjSReMQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:K4ztyKk4BKXLgsxn2pSQ8L5o9bRbq4YKAi0s6LKD2cUD7oSJFsVkH0afSxarjghz3uXLDcdp/QY0gL+F8xntjebtdyvNnIdZ1EMXvV9PK++HKLi/WPu+1QgbkOkNwCRKxbNMjEA/j+7xHLW5OduFvSFENVVerXKBBO4WUr/qRIgUPgXA+1mg4hsC4LIEEjxih14naZWFMWP81++bX+ZK+qQIzRAK06TpzpPM,iv:A8Y56bDfMokbDspJ0ZGDWYJz+xryhJWUtGMB5u85CX0=,tag:0QEaDKb4zUPumwu2Etc5tQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UFZCMnZvNjd1RVRLVXBT
            eEhUbDRRNWxtMUFHRWp6NnYyLzBLNWRDb1RnCmtNUkFOOTFHRHU1NFZhVisybmsx
            NnJjRmg4SEpTR054UmluYU5ET29zeGsKLS0tIGZ6VVM5UHNRTzN2NVgwdGswRCtq
            bytLUUhzQTBodnZBUWhlanB2R05xVVEKsxPIoByJ4u+8xdXB2/R3ASQXizW6qn83
            fvs9wMExcMVXXmwnzZpvHJhFyjmB8cTarZnZeOjMJORbN5tk4sMTnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T06:36:41Z"
    mac: ENC[AES256_GCM,data:TabWAqUS2Xncf7NTkkW/rI4aQJpatdOgzbyEIS1rKUqW3uvmZ7RakCk/pGKeC5/2DjloAX+gMMJzlMFSoA4GgQJ6gKZ4hyrFMXsvfemPTxDsDNVu1NXDBMpCDT0j22p524SoWCdYGqR4Crr7byTjOSCH7+g6w9p3lPFax2ymYJM=,iv:GDBIJORrAGiIqJXLYUv/3WPzIC2iqpQKkpDI8Rzs+k4=,tag:Ru5TL3A797sd/u+ten8VSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
