apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WFIHTVjBeSwEOZxtrHmHLObD0OXpTbgxKuqK6zdzFn80Xmc8nOGmxBjl1YYdFegJf+IGQFBG76Ytmf4jh941zYnd4ms0iiFOlDbk1WDcb5qIcUK/kH46wAkKnF2au4GKAAm38pG5/hD/crGrXYWHxQgtoX8hX7IEHWwCQe0fjSQDfVrrIyty0G4dL7SVRAwp0zUdhESMfmO9L0aYe1vzWuEYc7Gxjfl23Hpu7SIJMJeRXQrQCZHKWe5LfukSog3zguEYjsUH9YH5OxTFjzIxIJ0cN3W62C/oustsTWTTQ2whEP57hsBaWM8N40d5QpgXOjJCOEf6jvR7C/sdL1IDOEytjhxletewnVMGA5/VbACau6vo4785qMKsEd+SXQB2,iv:9olaAi2lQ7Oj1v0Y0fjC4MDJT537UDYrBqxfM40R/N0=,tag:9AMTZGKoVHloJZDT8Z3oBw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wxeDINk+8mJcYzobLmM1PUlqLh7I4M1dUT5FCSnRKky1/oLke40b8u2Dcb16glb7EE6gPUJokcV1qvSE0k6m6FyBhOaN4O35nlahXMKBQaGt1PELksjREuC78HN/l2zvJX2cDCxTvQF+6FWCBiQXGS+3P9s4rrG0c7gz2UkEz336OmqjWysC2o3Ry9yynxepMa55X1d/fBHO4ILiDLb3L/LhWs9hf+RCNUDO7fK5mmvyOIgS57Y5rMUcFVGZTQAr4hK0J6J4NNZX8WfVGw==,iv:2In9LIQpDyHjFHbc3II18WLtCqg0HVbyfSBwkw5svV4=,tag:/UHUfJh5KwZD1zsKd2+lIA==,type:str]
    known_hosts: ENC[AES256_GCM,data:WuZTRchVtnJV2uTDtP+MW0D4bsAhp9W/jPHLMJNmBYmOATp7zewsD2TxmtdXpobx3Y3avL1H0p9xMr5yvg/4C5b4i47F+VjMMRQmsj8o4xptPTz0FZVJ7d5KFou6pO46qZgBUL6vEemeFVPZyYWBLRLoyTejZjOoro+VTR7h1TQsf+4Cn1q2TNC/GHC8ecofnAKG5VnelYmClclinZzB9I1pctt74jE7MBvN,iv:v9MpU+8kev+7mvaHQK83gojfBmrdq0MTyXxeA8O156M=,tag:E5GNBqk7oKPazpnyvBHPaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUDkxaVNVNXIrTGw1YVdD
            NmNOOEp2OEMzT3B6SEVWbUpkTVhsNTBUYVFRCjJNaUNRSGhaY0NEWXUvUmszdlZM
            Q2d3Wk4wSld4cnYxR1VtWDluV1J0SmMKLS0tIDRPRVFpV0FyaGJQZTJNN0c3R3ZS
            LzVFRUI0ckJkWDJKKzR1T2tvM3pQK0UKE1OX1rr8GFGsSMLeYE7neV6OoHxe/k9l
            CwN02kyt1kLYfI5OOvSnQJpP0qTRNZEVWXLgTsQbo5PpBQ+5t+xoRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T01:50:39Z"
    mac: ENC[AES256_GCM,data:3x8OLaKS13QwC+WSUP8/BaR1hh205tyQjdKAs3NaRObas2uQNXWRSR9phGXZ+4TZYFCBVE7e0cyr7Aosjnd3uwqOoTUBfsztYIH6huexzvG6B2rUOIV4eu9tdxKpIKLF/fh+wrmX94c5qYZEUJDjaL36RM7FBXv8qtf2eqUrRpE=,iv:kqI4hUf2tXmhlA3bi8r0jWjxCx6xmDwG/+rBTMIKyqg=,tag:Jpoq3I9nKztBeR372XGThQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
