apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LpbBCN8EuFa9jzIGRYJoECDHlanDgOYCdmyCnGFO6YKH7QH3STO3MycFeDXdHaA529NgDRCDxbkAP+rFm+hz30K3uuVVDJCXWnRkXZgB5X2bVPAFXO0g7Jn6Fdtt/59yyzp57j4hBRGLQ+hGakW7fBfCdKqj4C7BEjMdjUcbZrDboew5q/JfcoPDf02IIhBB/9T3kyQ3QY93WZVE+780/ewCT+i8DSLuDkAm9uiXLR6R7WVk+oGegQVnqededdHhdjRLcLqYux/XNg15RO0khjftqgiXqeNgBZAYt8pk947no/M1M1qsoNnjRnZuAFk+5kmv+WdR+yS5tb3gHQpov4D5AiSfwrM8aOsCU4n/uvx8eLoq86OnxxExYiBIYZ6p,iv:g9nUrSylTu7MW+yxfPV6LebVmMwYvgpECXzKRWJ1r68=,tag:1s+yGF3lzIflUzsUIKNEhg==,type:str]
    identity.pub: ENC[AES256_GCM,data:uV0A/amevyEizZkm4tHAa2L4W6NWmvjmdytc7O1Qnx4ymUPA28OfheucJ78owIXs/4DtclkmKe2pH5pnyXAutthnLKiCfv3B3DCA8A4CVEV7RXhj0fva3RaJ6YZ/5LgjnFZDIJbyyt8wbPuwy9eMUUHDJ0zw9vDWyX5gN0DSeCnvHW5yw4BI+SpJDP8YCQuskas0xsYaNnZh1zW5GlWeiDg0f5XZofrxwET3ibGUxFPV1K1MoZb1gQC5bKyYaEVoe4oKU5uUn9eZXnfMxA==,iv:Lt3inkv4afuZ2PTauK+78/Zp1J7gAblqgiDiukYcTTI=,tag:sZ2K5raT4XxF6om1vdjMoQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:nGKkVZaWRDIjPKhTVPbhEiDolOND9h2NO7Sdv9PyGI1k4I8M0FKoRbaC0UQuqh1TXQvrE6k7pxuCjViEZzjWNNFtthApmvivZp9d2Xl6QUUV4c+WnBvYe8saEs6Ecb39MIUKnz+c5ivT9YgK8sqKerir2XVNccr9q5Uxlaofa30HXsVbboXcLl6Ds8x+oYQIU43byI+aJoaYnbyD/WfseyJoyTnyWFeJz866,iv:RhYSvRLqYUM1RNDvvHxDcbMgJMlP2pDJiO7T3kgmj/0=,tag:Iw0bXtl24kM6ulb2hil7yQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb09wT0xGdHI5YWR2b2JT
            TnBXa2M2aXFRbVBhT3J6cmd4YUhURzNwWTFRCkc3cW5HVVl1U0lQSkE0dEhlQ0Fo
            WEt5cXJSd2VCR3NEbHptYVR3UlRSSW8KLS0tIDBINC9hTkM1dEN4VkVWaFllYjBh
            M3Z1Wit4cGJtVzRtck9JUDByYTJwbVUK2yvlxGoU9IbVOy5MJmA1HIbZv7RKypKC
            QwYkuX5VAbOS2Ozt/v7POgk2g6DMXyYxrbW6Oc67ZF82rzq6EOWbfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T18:43:18Z"
    mac: ENC[AES256_GCM,data:lwZaDccEbsvdD6ffHZ74g6siDdKXOxp5ES0LjQTxD6heq6pixXKGgs0adVsrvxnyZdxS0cwJ3T6LG89HFlHrj/dlptpcHeZbzCrvdBHtrKMHHNR0KBY8t8Lkkm9fbIDdG1ct99SHIm3aMoageQnq7c0+tFVlODLYCgPYFl3Pw7k=,iv:PTrZumgDvzckX0e77N0lfAp+hwpfRv2woe296MxZtgA=,tag:CXgsO1edkKY3n95X3vczJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
