apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ieFaO59qsj4ZOwO/hQLY019E0sruE2nnN/jAfWLX7Dg43W9puJ3DuVzWY3Gyh+pyklmWWZ+7MJ9XrXNhQbu+KSq/kR49I4DzVGUSgYpxPEl2ERo3vrvIAp9ESGMhc7yuUIUg0rJpEZH7HyWYX1bVg3STJnV+Fk1hNr8sb+8uNjDtFyN6BsdEalFBI1IDvjFqLn7+CQ8BVN030rY6VyKImiNjJaU3Ot0HBgfmN6662CQ5hVZbuUG0oNavboNrZB0tyAPvHx56RHZ9nbfd8KKNnxJcnpEDUAvVa23smCHwhLaqZ4vvtqaCu3/Z/x9Gaj8FPw3zVAkCNZr383v2q/VoHKxlDVYM2vBOzXCc7JiExaWSO4BHG80w1HfXRlmwPc3q,iv:FY2HIQJypmiJtElxW7bJ66kwx/NsTGzIQNNwdbMuppY=,tag:VOKlNpJH6z+xDxSoSMGgJw==,type:str]
    identity.pub: ENC[AES256_GCM,data:dh5WA3hX3VIqxYrqL2aR4T65oEVqQBDwkGluX+lyrxC65RcviLu1mpS7n9CL4x5DjWXLM9Zh6aRUsq8/pNig7IR+mwnCAT0l9T4c93386BZeKzUktFsQ6qS9fVP08q06c9DbDWRMbMPfP/dM2y5aNMMUHGYMh0A8JSG7Ia/Z1wX15U3jO9UDfkiuWekAlAthWu4uUiU2fnfrPjB1fM+htKQ1UT3JekHsE10hZY0MeYX8MDEcp8kVV59ZpKDhsQO5SWPhbO1YGi6eRhej/w==,iv:6X3VxzWuAUlLLNt9DRKt/XE8z7dvNrJkKxrfRWXj52s=,tag:GcE+3J8BgYqMNL8d/eFncg==,type:str]
    known_hosts: ENC[AES256_GCM,data:GJHFjO7hn+8oMEOK0pODp7i8oDpe3rhYy36xO1HdoSeKCwLBQsLwr03t7Vw+kg3S8YeYw7+JLFb161PtoeyYmvAJy68KYTQGtjePoRel+7Y2qsApiDFJOaMgPnN77Y8BNZxTeyxd2zpDrUlXoq5usLJE06+qp+O4kZlr2dxllGb+mNd98gBB3V3pJB+P5VC0TygmK+SrM0xZwZyh9mNSg1m96M0CVFdGERDa,iv:9cSHDWhyhOXs0cLWlm2bB9zMl601XdL9wOIBjB1RVVg=,tag:IAkAUw2MnQg3pFup40j5Bg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMHBZQS9SVS8yUWpBZXZU
            L3NIT0hwR2J1TE9USzEyb2ZVRjRvMEdmK21nCmtUT0RBYmV2K3NuUzdrVzh1b2hR
            VWNyR2UvMUhBS2FFcTJWa0hlamZqcFUKLS0tICtNTjc1dyt0Vnk3aEo5a25tUlB5
            b1kyVlI5ZEcycWJsSFhVam9XQ0tUc3MKCgt9iPrYQ6tHmlMYd4pY1tnggAGLLouP
            eUSL69S5lP+4PMoybjWIXMjoN1pzjuGN47nZaBhve2yK4XaXveoG6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T21:32:26Z"
    mac: ENC[AES256_GCM,data:Jkq+P7zCasXs+We1x5oA8XYTP0Su+ugdjnSQ+VmVtp45o/fbZTs7Kak/zlc/6Ezqnv3i1GoKn6q01gliMZ9V60ekiT3JCrw9kaRBFS4d7mYHleBkNk5fLpK+RovnF4w3dJjvvq7oKzLXnth+TueutwjHB4+pvqYgI42/0h2AxMI=,iv:f3Wc4akgCTGUh0cZcU0q1S1ztiDM0Pf7xImpt2hrgvo=,tag:YlMRrQNttIgYht5pJyHjcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
