apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vxnWR4BS0gvYOfdhpuYNhtvpYYqtQri1mKwwdQc0Wr+rMCx6eJJvcjMCPh6L/fUhvMMzecFeOvAL4jGc9DdVET9+/AKwvGHDDnkKoJgY6ro9R3ftIe0W9wUz7FEhFbjKAZcwjlCMnvP7PmF/vjli9jeiRQ/a+UMh4TjhpdItNx+4DTKc5aFkjTExkhR/+Ojnch1N1QJ6BP47GBgqCee7oLq99+P+jhDuW41i3kQ3Zix8b41zHuq37ZcYskQJ4rZyusGv3C6XV17MjGWoSTDNC7hrG68pyLlB/eFnI2xm98sMgRmdsmVjpQwaSHZ1qrDASKJ0domfe5bpbctIoA5BdjJpS5UcJUciywFHFBpkTgSPfy4NIgv4G1xJLZAgDNHV,iv:LFKdh65vG2KLFmXbubjNhiImd5EDdGkoRlBIY9wb1GE=,tag:mq85cPML9l/XF1VOF/FVtw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Z+lGAesDXLG+QIDQjr4Q2TplTfsJJ6E26ueebK/dcTuQKCn7SSwA+W344tcJVaeLXB4imLjL+/c++U9WKauLNSnJZhOIXdNkwNXrLEFxTr2hGtJQLvKCAz/hQr+PQctUKnND5GviIHANFT2BQNo3uUWpZYOuS06FXl+AiLkanvi36wBPA+oOHUuqyVbSL8cFnKQCDHrWyI9fXvtrvhrjD/JrLP14IeDeDYTDOdII8CN3mGwGVN5Pslgc4Jb942cZyhucDEDnJoQNIwH0VQ==,iv:BSmgKRRQSKlSzGtjD4U4uoyZAB73Z6I13L2AunXncJE=,tag:haY/NLF2TjuzZDZxylE0/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:XtXlC2Uau7qoRQ1QIjfEoEztdvHYE9A9b/UwQZA35xRpLPkYRd3Mq+iC1ysGJkIq2bZo6wjDkn6vUctemg7+ECmLZ1lt2qsZQnXclfcUxgV6ADzWx2kLEyil62gCp+ibX95gWIMYLag4qFajnNtwTQsZpcWwEkR9FBn+FZGFU9pWDjKIvJn9HE3dYffWBEy1oje4OF9VJGWdMSCHhOlRnsrMUlIv9NG8J1L8,iv:dh20+jS5WDfuOypSOT+3chQh5lGfLZAATNDQCTtd1Ro=,tag:C5rQXQECckE0w+a2OF3RTw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSFd3NVg0OE5jVVB3MWEv
            emRDS1FKSGkwYmljVHBmK21PZWJjczREUmw0CmRwSE1TMDYzellHOFhJNU9qVE9O
            bys2elZzZzBrNjM5enhMcFhLZk5FS2sKLS0tIG9VSHVLRUFiNWc2UHkvNDg2TUE1
            Nm9KWmJBYlNFTDFmQmgrTEFHRm5IZEkKhq3+CM/0KXWEKz7iz4rqS5L7KJaHVWLx
            kbaik3v2pJMFG84y1kJ/SIUhjMSTXPIy9gC9bLF2zweuuaZXWp743g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T06:47:32Z"
    mac: ENC[AES256_GCM,data:t9c9ejdjQSe5KIBp1auhnsEZ6X1nTPj7veWgdF9Bw/hAELe3IxZk4rT+4iXfQrQ3NIvTmzUoBacu9p5TaKxz9zb54/1oX+OeAY/kYOOX+THtFPtxzb1xGLRoi0TF9AnCFKDgbkunoIP4yASYsVevCnwsvO2N/Ld9gTFeIQfz8x4=,iv:cH3PdxTkEG0TvY4hO7jM1YzSXbkpOSDUsL3KIDT3boA=,tag:7ZZfwiXViUV3+Tl8G3XSrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
