apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tX+trkXXn6nGXOc2TMLPVliVsNU3UtGHcwjp/14UXQeSyNdiUrM4LUpZNxTrVnQ1xF6061LZstUQsJlXciJ8X/PnpMwfuK0RfwBswsot67/xKCdjpBFJ9RUolP/n5Q4pVOH0jKhb8+4qkQMD0JulQd1BFKAia4R8aJrvevOYKiSqpgMQJ1vOyF4oiaiwGiXcQQclBWEFV//B4va4iRltAuecxcgd/DwBPUY3g7s75wYSiDn0IzD/zAgXzK4N8gkOrqB2mcotKa6iZAC4/hcdmbrEvBrlMtbhjV8ECwwp41LrzA7ch11xsmwwSY9SXshh8kNNr3B+KeYHYWi4sww3UVpxVFYvZRNrBcqAxwn7h/GLbsV2DBcRXtGZGYucrq+j,iv:cIh5cVYIZ1N8FLwKe61s6B2NRsS6yXBt+5+RCgSjtFw=,tag:xF6E9YuUqcDdAgZ/62WVQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:cm8H/KoIrIRVUScqhLOeARDnek7zbKBKUzhl2l8/HF2N1zV/ihY4wzesYhq8uGAMVtfvCsUkTpY+Ya8uE7mmvO2kABOojJ7e6JMTyZ3dqBv1MCdg1m67vEUuTWKEG03tiyMVQRzJLeXfLQTWU5FPdoYa6n2hv1R9FX2H/986Dwh2QJozsiDOxhXWWwqnFqoW2xCUjf7pWKVh7L+2tA/ZzP8olWHDyGyTxUgzlyWB/TOkbvZ1Fjsojby32nDJ6WoawIubQIUZ6FriiPI8uQ==,iv:+UpVUuFpslsTz73DgXAdMDbwGaAZMi1ELsJ9yhN75DM=,tag:0eE7Zpshfm6vE10ozyCW9Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:SXVymJUPBJRtGqHDQwM9tV/A6IJ2cSONeejoWMP5BAKkVGaEaLUREHHZJ2/51zC0AVtn0FRhVqk1snHyN+vlWXRnlRJfzHjMUW9IX0hSfmfj8WgT6phHMgWRNIdWQ4/iZfRDC+bSZ/Q8ANOuDYXehOPTaPE6TUiJ3df1HvT3i6UyCtPtfBFjs7eFAn0kCVzqTwaqkcF/DW2E5nauoW8kuXjP9Qy3z+2o6Ys3,iv:7Ietqv3itChM55c9bt+4MtmkpX+Qq0DWC/ZxxC43FaI=,tag:hbIwVavmDCrpaDhGbomw6A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOU5yVDNKZWk4Q29hdWcz
            amNtREFtSzdCRmFvY1VXeUJjNVF4SlJRcmpzClhaN3FVb1FXRTF6c3ljL3dNMXh4
            YzlST2ZpdUovWk1MaHl4aU1GQUE3ejgKLS0tIEJOVHk2UTVIWms0NVUrakdmeFNX
            Q1V5R09EUWlra0tyTjJveDVtdnFRQW8KuREpp9iO6fgI6RcS5ThKe8pH/8TCVRoG
            11MHGiCoaiH5GV2xiZ5IVRrLKjFn5Bdt+eXawRkA7Y50xOH4fTh25w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T02:22:26Z"
    mac: ENC[AES256_GCM,data:iscushc5NFOmebSkvUKiU6NYIUbf+UNNHfBgNaGmYbDknoehpfQuHKQB4xUQ3CuzESkqienRmpdZ36DcOKiiiXZBzBxJjOq0RGyHhmVUDqGzMa3plJhG+/2iApP+tTaAqJAG68HvYNUJB7KOubk55I2EMspJ/uh6YssRVApRwAs=,iv:vrtWB518ggJ3m5Eys/6za5shleyYtlaMAPHAkC0t1+M=,tag:UTOclcfpYNudO8s5DmbWsw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
