apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2SKKnU5T+Fn81pXiEiLv2RfH3UTGUYcqdXOvX1jVFIAu6+Oz8kXB/+96ZKRQXhbx6M0O4HXyzDJ1SCJvAAifUJNt9V71RgLS5rUQMXwgilqpjW1hTEkM1Eix2MOR9MbSI5o8ujRSACgd/oSQSn3ZiTglCOB6Ih3cGdcE1gKR9Ora/v86iGA2rc/lmOlR4aibIZyiLMkGqPFHp3zc3iVS1NhtSsPelz02qoHJ36P0uQtJDReGmbZ7VraVt+hDfRJ2WgZpJpxEn1dzRzU3eoAL19cpLuqnwT52ncM2k4GH59+DQCy2HaXpa8ps4h5IALfo2L834JA82BjMCyXV4+1798knpDCYgLH/t5ozwtUrUZqWcZaQibVv7H5Coi8q94mV,iv:66wqwt6Y2B0Bk/y7JSyj6G585y4Woe9GQd8wz/PE6dg=,tag:5HQPXKyuyAXfynyMa402fg==,type:str]
    identity.pub: ENC[AES256_GCM,data:g6D2GE9u+YYhSCIHOqwjXKkHpg8x61o/6MHa5y36GeVGL/bIMcKoU/HaXK5o7vsVweCYpaPYJM/1B9uzrqTMUcsQDN7xtsMs9vWb8lbAOkJHLJ7nJeIlS/dyDkEurX2Ho18qaRbDwYd0L8RWoDEe9QxJGZemZTTIEwoNl9/vymmsRmrFXGi0pz1hvf4JEpfDKjS6SdiFyJZtv6mCa7F2S2SHXL95zfA1ZLxGm5p4Mn1bCBmQP5tC8fEiK9OvkgQxhrQ/1teCXD1a50tmbA==,iv:zBxTFnoBEcZNoYT234QhBEx2RsbXhNSCQYy6xx2LR+4=,tag:hykzKss9KENVhwnfRgCdbw==,type:str]
    known_hosts: ENC[AES256_GCM,data:4TMvNJ2SQddY/h/tJbsiervfC0H6668Dl0NNt8vipQy6Eey0ogpEd+zQ/JT3iBO0myMOH3r0WhZ64mtt533ddF4sGdXlaLtI3iOb9OrtDXbV/wH52xZ6K4H8IM/xMydIDsFI9f89zGMhJpTNoDMKSN8MQH7h2ngY9QmgLmmZLLV3vwtpnxMUJZa31gE2VDKA3E4aRj/IrA42AIG9UI+mC52xoJkfJzGu6oS0,iv:hSMdt+d8dOubADBRnj9OCZnkvWkoReJsfnMSQpLSzhk=,tag:ZhcBSY76BQyGEkf7V2Ehxg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMjJrakVDdnkzbGd6V2dp
            NDdvQzNHVHkwUlFrYXVpNnY5Z2FldVRiKzBJCnVjZDVaRnlDTmlvaTdvTW5CZFZF
            M1BMT0ZKNnV3TW0zTFNaNWwyTTl4OTQKLS0tIE85N0szRXM1N0VQVEJCRTk0NFYw
            UmszUjZiZmhFSSsrREhIaTgyNGtpQXMK0h9oJftn1tomqxGrkneA5jxDElN2txTQ
            IgZC8a1CWuaoOgxKf7+JgODM0NU2wNrDmHnrjKL/rbUBAt3jdYRBUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T03:37:33Z"
    mac: ENC[AES256_GCM,data:6m5NfQmfKeL1sh/LWy6577DZc6krB3zLRPKUUUPaoVLdc+r3xq8B8FtIFmWP9UsxZgEY9vgCZbF7lW59XS7M0UBLj3RBRPnYtsAC0HsYzudvbqklMayGmApK2PH3jQnXLZOnlgI5EYKKSkXHDTKmmpJ3GPWlEhN0zEv+jaHfStw=,iv:wewhIlbeN+J7HThN2Xmn4vUN44Ji9BOaZ2uqyxCl9M4=,tag:Y88akWm8PzFGY0bQQuGLfA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
