apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:S9foQomVYi7SySCRl8h6hmQQksRMYBLMZCF0iv5qhqihu2GpRnojJNyrs65xrgc3jOMeuX00ShfEzMjyS5wIcGpZNsB4ywj0taLifjdMsVC463B3PQdgPKB1Ffi2CZCv0QT465BOeVrsS/N3jSac61IJCYM6x/WYdzd3eUmug1VM7Il0CD7ZEhX3ER3CT2qqrnQzPhDtYPQN1ygnCGxRtyJZ6ZFuuIcbuvKvgH/03ZmVtaV1gvRopX3qNB9iqrkJGZ8NWRkspfyxkyeeqGSeQ7r5ylf/3Mu+bXsz2exo/RMN59l8+fTyALsEumu5SbGpBmNEw5vsQWClgnBhWSnL/Jbe8zVA3nHuvOaa7Me962jiG724J+Mw98/E4MJYRz1o,iv:KdmFNYFcvY/hJty4TVg22DCccJxZLzhV/mQe4IgiJqg=,tag:0ChkfCxIC4uQV1zJYUaaQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:9G5xkI0MCiFUHi5bne3LQCnEd0LtySSQoF1JQn76TvFM86cxRZscTEoSbeEIc7qngm6hctEc2Q4NlHPHLTWPb/+WRkm7foo9dPPbNfW7thc7O/K7RSk4bJRtQvm0yJzAStG+yb+pMquvp1R3dRAmbGnNYK+bXWvks7Jm2020W+1Q1cbsFiTJ/KMmIZxG78tr0CY4eMqPQsBabxj88xyfenGqnYBwFAKuuzYSyc4oZFcRV696ZoAju35tQn99q/ave5J00b86OFhP1XxSPw==,iv:njZGwxxvTezBYi3m6wdE6SpDLPdLte+ia1pjjRBUnmI=,tag:9t0uLfB+t5A83F+WxFia4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:H6MynsHyfs2a7fsgmyo/kVq+7kk3KRiBNl3NrUvtEvVHHijbwMzXAlarYA1SCX8AnsUr9rgdzrRK+sOKE6eLV2AwnbPacxRPkCnz4jWdmmiq2jH0xqiI+pZg4aNggOlDm/GkZZdM6ORMKWH/zJjYzKR8CtyQI0wtZbH00Pc5o98HIaFFNc2+N9VDwt25YZ3TNrYIY1ISMH/m5Ln0belMWlvmdOQ3N2g2z+hZ,iv:wa4jt0V4xf8yOAAvU7a5YmLkyIeoqbr/rFNXxv5GVyo=,tag:Mh29a9NMXy1OsQjfn/fNOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2emFTeTliRU5XOHFROEFZ
            TWdFRERVN1pFeUJiMjJuTzRoeGpGeFdTZ0J3ClZPa2pEVCt6ZytMWnE4dWI1M0R1
            MWg4c1dMOXNmMmVjaGpNR2MycTZjRXcKLS0tIHV3SzBFbTVpVlFmRzllOHVtL05u
            NGdZUndqM213Wnl2eDJ3Tm4vQXhxV2cK9JV1jFS3Mkrl5P9n9aeCJMuZnB0QrWNS
            VN0O9o4kEtpKu2uxpi3jqesvU5GC80FCZPkPEB+3gmPlK+sZF44sAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T04:32:08Z"
    mac: ENC[AES256_GCM,data:JwI734365oWjCwPmvkxs5rkqmSZw47GfsSKZHeU8BySG887/KJYaoTSBHYWIGqUtP5TSGzshcK4Ka7K4c5nJcUNvv+B1FX7XW2YtN7plrUIHXdXI/xjZuUW/KIg6HkiJAJbncfLju4wr+38Dusy7iq1cTpjnOX4DKHYCOG67jwo=,iv:f8tM2wPsBF7HqanJb65LGKxqwT23GMm6vnGYpDFJu54=,tag:X2qjInY8r6kyzzAi5X6ubQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
