apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ySHqWelQLZjWYk5HU3ChfapU1V5OQwLZFlJFBXdnYulcM7Do37Dh1GgKcj7ewj8hGbRj9kbS5Zx+rKnb99bgU8udFznuD7KmDD2P+RDG5YhfhhryeILMl5fkEIIAF1/zSBsAwhaYLjkLvK/v+Qek72jVxQh/jC8jD1VxWZMfrkEPmMVu/hjQkMWJ2HS6MhZC3d/5bTe477fdi9AnPxrxk/ksWqcUskqhpi25FgOXwvH+dR4GpEaGTgfFoupOCJFQ/qCvoBydHzytI1zZIe2u+0Ek/1eSUDLPSGsy6Bc4l7VcFV7vdP1ACJmJkXJueoTBDJU/I/sA+hN6rGby7zllEF4mWr9CUOls9gAP68P/dUtbpE1R5gIEVgnuddKkA0ac,iv:2mvuWyWaBy4mDAqrivMd11V3/O8hgmUlkw9zQ39ZcPg=,tag:PTaDPS7P11EztfKDWgn+jQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:CG3rbpHQ8Gs8DiKY3nyx2l/n+/rAbv4uYQIaYvrRxPZIJuGxtvDygRgyiN0w1q0XhFQeFmyQFZQ1W/iTqkvCBL2Qf/xXazbvSpEgAQJy8g0L5Qat3Hk3ObgeGe34n3YUs5tZvc9l7aZ2pt50TrCQqMMYiJwC5vt8PgZsWp3HUOAwwwxRygomrkK9QhqO9evRTzlNxJhAaysnHr9EeLK4LhY4aw5Kfll3cYtetFLWMBBNwTXZsd9gBofRSybGvMZK/3EovNak0FF3m24lNA==,iv:A18sNOC/Y8WgxIBgq0It9SdfDNyi22FDOWo9uOyQT6I=,tag:qoZWMRJFhkb3Ggf63tul/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:OhDA/VsppN5q8+0/e1Gk+CbEgvqHWzO0/hjPTFHr03naaJz0e4TS0AyGmR/e7OYJub+O0PjFVLRUboYSunLFU54HZMgKDPYeXaS8sIDFNTTD992i05fRDHnFd4oQIHfNpjyUjJh6BqCfLBU5V+lk2pAWfnal0wLISmVMgn/QR6UJpYNdhGOtVs2MVFAYqPalfWNrrtwwIQcfiCt7vQDdeixy/8uy5uiYuNOR,iv:Rx/rlnfBSsaXYRyYp0cLaSf4tLkuWcxeUWzssUfX34s=,tag:EUHxta7Lx+R6rNJ51/z71Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbGlDZlZCK0VnaFdOYlJn
            QkZrenZpY09HRUJROVhQVi9hSFkzbzV4aVFZCkVFSnh3aTFyc3phQmhMRzVWNkZW
            amFvVU1TWXpNTHdTWmNZcjFKKytRMGsKLS0tIEZHbXRjb1NmbUcyN0wzWFZnd3Jr
            MzFhZDEzTjhNS2t5QUc4M2EwMXQzbjQKpeukPa/hgtD9qIy7SJbac+rwxpLLFeXK
            pmleeWqAroiBjcBOlkPue9ByzG3QBm6O3I8QYPNDh6+Ak09pU59HDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T20:48:37Z"
    mac: ENC[AES256_GCM,data:oAGbuqNPVpWC/Clw5qIux8wGdoPRmRpH1oPPUCbKA99mxBAPMr7VayyzK0H8iqsvNcFZPj5h9ewGJwbaaCgwsIdLeEXvT3f0mPyylVLT8CGFpFQY8bE5hF8TQY+7INjUxhmh9Li4Ci9Dktn2m96W+peRgpHAj32c3VnSte5qNUU=,iv:sFu2D0G5oZeH0pR/I6quSWKaR+Kyw3rR7/Aebi+GFrY=,tag:RVpHkM8b3Xbszuy2kn7elA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
