apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:k9wZawUQ042WEj9iCs7gyboxlJDFQYsmIhBPJ5hZWu0SzomWFwUC5blVtFb8MiTB7cp6fRWBd6PtCopjCbsSyoSuNkA5LzbARkjyebDO5JpyCt1vA/8iblWtDsKOLqOocPt3cb6hrQblLuLUTfau26fk2RdPuHtXao8OBVKA461/BXt5Pa/e/vu+yA5pUxwoD/9BMmEJ4jH96iBT4VlVb90H4FcA0PjSDjKO+8MvKv5DvUCiTK4PPlpbKVq6T08R8FwBqMWH5lJWMozBfw6cPnoSCc4yf7wvOGv3Oc/Lj0tYAOs5PHvhJMQikyhkgyQY6KL00LOGsMRZ/OUJkoqFhWZn8/8xA+3ERV6ycZ0VIaqQLVPX3fk6NlsAlrdt+Tqp,iv:HO30S4tSbpnYRQPWBGcZK/WL6inACF5sVfbH+l1mQ0o=,tag:CNm2IZfhWwaz8tZT525y8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:JlsNF837VxSiBtU+bT2Ksodv2JmpzBiY5zygvYBdwy2CQk4LxWQPSWrSYdCQnknL0a5w0s04EiB3iYk91FiKsFx6ngDS/2zHCYmeR6GF+WqMeRIugYNDQuQI/+pmgeQYcCm/zS4R7cKfLOYaaBUUI7896kCQC/BPmwx942gHlsauqbEJdDHn3Gyq+mS0DvpRfZCJWWdKiIyv9ismsalM0O0/tiJgkm2biF3+rpXYD9jrGkaWd2Z/UZ+2NXRJEo/APQo/RJ3UVbkEbOYNGg==,iv:AfVIpDtPWDJboR218Pl5eAuux0F0k0ReXsgcr/xXInM=,tag:mtKcKj36BvccB/s6yphD2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ek+SH98QzOVrIa1QNnz7GCNuZsh3ABc9xq8bK/F3k3f9QlhWvmCl9uLhjweZkbRIPcX0yj5J/pTlKvFGchTP3FvI2LgnSqFwCmwkbuVTIXx4YzQGHMEn+hjxVUEJIpYvJJXunqYk8w2fWbyHX7peF1pHB3cLKI2N/lsHml5y/6kL9xj62KzRrt5T2U42fPuBbDePYkF7D5tza15mg6wYWGVKPMLC908Bbeah,iv:ZCpmFE0COTj17lPYm46RU1BE53NUw0ssKN89WDaqLfg=,tag:V6KUMvqjKw3bYIW5bDaMIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT3IxUFgydVQxZlE2MWdw
            U3VMZFJMbWV2OFBwZlQwa1pVczU4S0l4ZGtNClRGcEZNNWloU2RyVHVrRWRqZ2Yw
            N1FBcHgycnZ4ZnF2bDlTcDV6dDdKZHMKLS0tIFh2cjdPcmR0bmJkM09OYWVPaHVL
            QXVzN1E4b2lrdFZMVjdQbmJ3THNWMDQKV1jj230L72eJOqs2Bt40gxlfvwi3mvqn
            rQK3YDvgUvPbrmuPLz3LENa90sFxlpDE+VvArzjs0YB/Gj+YVitqdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T17:39:55Z"
    mac: ENC[AES256_GCM,data:8pDOoWknHR6a79wSYMLT/+N5ozx2TI/yyJ5vtJnYkE27/KqLYLNVVSBzpcGhIIXbg1mGaMMManYujeT/TYQN3Oiv/uhBXIE9V7/fp2iGOJaRGq+6OeSZfvavM4ACtD+ciewDwvIt4OIyNH2Fs/grqGPwiJRzSohTX3KmRUa5abQ=,iv:j75k0/SsbwqIREkWcOaSdXyPYWUGeWjvJmebh4fOtZg=,tag:eoodlTHEXdIFYcSJixB+7w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
