apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Kp8J73G/GGws9MkvspcQjUCYwJcg1TmWSq20XYCB1exKn3Q3dwphCxRyxJX/aZRMfuqzlxJMyKu6YcLVPHxWRScmB9+vNaxtby6i9Ar6+SKP6LuxBRHJkaJpNtKz0oYgIHGwcvhoIsSemyRGmMf/XwbFLKfW0vWRG22mHFJMcD5y5N1RQ5kqjwYoyUkyvsBx/obZMoIfEgHNvNTnkllztcBgqh3PxhdcCI14tefkn2ZHb/E0pzR9Ztn0pF2bw9rowi3xFMYEeWJxNd0nfnIKh734nIq7dxiNDHu4aLI7en6TvzKoUoORTkriiv+GefqjxORbqg1Pt/OpaWxXvTlr93fE5ThMWnI6QzXQpNfK/6/hsEN+ieUuqz0nFAcjhGiy,iv:EkIjwoM5PQBg+S02x3xJZLSSCTrVjbI9KgTDeHDoYus=,tag:nbQjmS8nhTJNxBP4N/BmEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:IXSTQynaPBjfjVK3/dNxkA1MYoz2+WiQlOq17nqDh5YtGAS9TBLIu3rq5DzIrHZYCeOnsCZX/kt9rJGGwJuiVsxF8acMBl7a95q/9eu1mQ4wcyIE1xOr7x8IqxujJYiK3TsL7uLBSMpUsRyDNx1gOaSqoG+M07bDai/PSGJ78sV3kNm+zfqgHsQEmDGxopSQJ8RgP7ZCAflXJasiifFS/wQARFNIj9QUslT6C2/0LmuwGj6G1Ux4g+4+VuqWUTEx9rqEsXzn8ZU2Ab3WEA==,iv:xc8rXfB8Lg7GLKtIlHg4xbsWuj6fQLiIneGYqwplA1Q=,tag:BMzrin8wU8GZXfcLbgXhyA==,type:str]
    known_hosts: ENC[AES256_GCM,data:qe5GJgT0j1OXWyKyxNv2u55r9YYDjleNnT/AZaGW4k/d3G6cbj0VBK1DWWf8WbFcKYGo/ffdsWUofvf86HZ70lVnnMVIkBi44s8hD7J7v3IicIXZ/8N5Wu3y05wbcwYJkyuVQ1+/xSSprix8LI507ymIw07fRIKnF+lp4958lAw+Uhkmzv652fatHMGqc9Vhq0DiUm5hOFuLdReYWt8TUVP1aCOhF2VBVMLE,iv:pS8XhNy1+4ZBwYL8kBlqqPcHIXBD6V5L2ZzQAY/63mU=,tag:ptS3WtorNFJf9jJAog6RRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaklvK3E2MWZUZi9SQ3dp
            M1NBS1RNSSt0MUIwWWljMFBmUkJKaUk1RlRBClZSaDFQaHhWVDg2djJTeHZ3aDA0
            WDY2K20xbEsxM1pyUWlJOVJhQXI2azQKLS0tIFNzc3h3clB6cmJNTmtHWUFUb3ZW
            UUc5QnBXVlZVc3F5azE0ME53OFdQa0UKWWzTDLAEUepU7fJFa5nhn44F1VmbLpqO
            udXn5Pmso/WYPiOz3HA4yQCqcGWdvm1qkrzIV7j39xF1LLfIuEGWIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T03:07:43Z"
    mac: ENC[AES256_GCM,data:pigJuCRWU9Pfn4ZiBWKIj8C+1sh6JEhcZKfvs1qmMbV0vG9qF2ekqybX6017PnrPO5jCeprt+52ZLDobCmPKcnXPKOPEJUmWtxN/H0yC1/vPTB4/o2Q8vBfoVAojEIvUcylgtM3MbqqxNaOoxIK/A3GouosYjQiEOOEX67zzVyM=,iv:S7JUfuZa/Sce2IwbAyUp2DaPj9hlaTlrHwPj548AFMY=,tag:FtPh0lSJShITTtikjscn6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
