apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tgT/v8lnV44aVwDrVQ+PeFlrYu5ZEUrnK+8DaRUZDmYqkm+aW5U/YHuzQnp2i6lHj9y9IkHoC2KN/7zb3cyb9LkDdoWW+wwfIgKF1+yONG3qng8Ci4WREyu4Wwo2i8txTCZBZ+JGOFGzsdu19Xw2T/vEo+50pMs/w9t6yLZZse9EQq7U2fQlCPtlV+CTUwHxTD4dqOtSK31fRd61VAtMVO5kc2QuVzwNwJFt6VTi6/cFN5G6DZ++6GDbWIThxJp/PmkCv7yNsf9C6Ln9/ZCoBBDVROpdSSscG0AZ+tbwNEJSP1n1pWbNrR9Cpj+qHgGP7HwE79xfiwfDH52EiT57BnvRD3eEI1Wgfjq2cv9iYAVbY+xHXBJjR0+DevdXR3eX,iv:sTe3rSoceRbmKwGOz7Bj7V9nVDAKQXudoe1nfwXitXE=,tag:lolxXiUgk4Ubh9313sE3OQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:pAf74VfXpKA7W3EpqvBVGnJ1J6ZrZC1v3ZCyerKLfDinqKWJMr0rOl3ccLdBn+LCcxAOF046XBlodVDpWaeZ4K3DABeOWlJzlun0Vjx8rWiXYi/lMlUBR1eFnCvoFpQuRU9I+V5aWdNTmA3x8oCMI1ciJeM5BLthlLo0c1HbHh3oN1qW/mMbjaBt1sSMO5uxt5WrnJdWgN/LtCFREfd+Fi2kZ9+nOOt+pO/6wEWVzjSnlRfCf1XOnwh2hN0C3sJJpzc1925Hzgn2Zj8c7g==,iv:sptW3IWxG1RK4HKIDmGlmdT7PnrnpOl2Qql8SVX5cxw=,tag:9+SrIABkd4liHqxwsVk5lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:PRaZnadhMeJFf4ApT3OcO+2MBqsR7romGf8Gb3QpUEkvqqVy2gUtsfm1CyNik/nVD+Wq4d7OR8pKMkGFV8uyyMTCuZEaCfLJ2JUdenuMQCfj+jzGYksq3+HVLnWaU/uvqHP6fMU1a3dzUyf+l5AHzb7HhnhQ1biP0jgNAcI5xOx3tyR6FsgKwPS/qth1OQr5M2sM8pWDDEpZ7DI1kJP4SHSknHsdGhyt2ie+,iv:L6DnDNHGG0lOg/PStodBCpBo20fW0L41Szq+ocDVhm8=,tag:h5W+oVGORy5R1ck7GW0tqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVTlPQkJPWUdLeG1QS0NN
            OXZ3MzcvdzJFc2svS3VLTmVaR3EydFVSSHh3CitCclVQWFJhcGFkMlNnMGZrZW1a
            QjBQUFlEUzJ5bU9ya2dKNFZmZUN1b1kKLS0tIEg2ZUcyWkhKdEJLMUdtU1N2NGpk
            eEx6UDZ6NDBuZTRVaXhQZ2oxaVBNSXcKEc5UGK13qgVzyW3zAB1QSCbfZ/4/xNny
            h8d/C3pV2hjwiSmDerv8jdZv+akwT+HvyUeALLMcW5Lio+062SQIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T06:19:56Z"
    mac: ENC[AES256_GCM,data:X3tJT/UhYWPXg2p5gwM7qz/4xUX99UCwJu9snqgnow/4m84KQElgPmZCyCe4ZeO2SwO6a4ul2yNMuIHyVFNM9EI0/wzMDJqZQ7Jqdo1zFh7PejJFwjQOsZe5YXwXHuKDHZqDHv/3Sxi/xn0z7BLyYcWYqvzBlvtnhnTd0JFHDXQ=,iv:8O2TzlyVtPOysZTmjsjXrXuWkRZztmtx9Nurs3WwjgA=,tag:OTgUxRHwwoc/vwj3UJf7jQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
