apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/VL/gSRQCFN3VT2mcRG6MjxVNpkFeQiyUK9R3bD2ZiTqF6Tgs18gCl0kV1HOM9+4h959tP6pgY1dDSMqqOlSM5vTmnglDIfeXX+c1aL6ZZ9L2MdUtZ/7tYH6FcXMmntFPfXYY9S4onUTG0BayDgWF7vaSfFocUQEKLC5j0XYonWPn/O4u4I88XEvE7eBU9v8vk4bia2BKAC1ypS2UsJo1d3jMAXitqCC72p8d6bHHiYz/5S0KLHJONrdBMDl4iF9p+IbtXLxcfwqeO7SLZo8ZI5wJF19Fc/Y3rj/VH6dKtq9R3PxjG8WIyiuGYPkFrx0HPny/A9BxDTv/xf+O56OTnFixrZmiQnErBbTI56GABoZvQcfHdE1IaeuFeMe6x9s,iv:piMDIoPmYwpTC2N49Ph43NH44lZDKsxNgXtnOlGJcH8=,tag:9AWLiNjfwSXoRDzownNIOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:AT+irpCujstGo8PP2bir8DUinB3ZUjZb6csMAujm7NXiUN9uZpAUKAtrGJm3iIpAvJNWcw+KEKMMPf3Oxcqx2ahSmIMlOsZsVqiRYwKYjkJpxraCTBt3WJxY5fDeKg9HvZ1fyr6xNYoM5nrrEi3Fy+iaqIkwi+9CPNTL+tnOWnnQdZFteEmgguK8mgZuACOp2u4e5oppNtPE3QtrgET4aVgWeSBiHtHOhvUx2ogzEZS11LFs8SitzoHP7sg/4BN6bVNiUxfgKXFrujDxcw==,iv:FKgIgV2JgTackyUHeSHKDTUKiIdNKWEDZnEpzfzPlTQ=,tag:RZyv/uh6NNUurCRI7m5s4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:tprlvwesLMOyDMkGednyGSdr3NRp8WRpFjYXQd2VzyuCkKm7gNkbYZvPhHGQ0Q0siEtGe++++kSF/u/3kECVRAX/+gMbvoAirzKa8zItVOlmvNPGXEcHWvfCnVhEnfJqPAQ11kfwjIh//AigymTOSiuZVwdnaPqxdCfm+7gYorV7fi7eMi+rCJU3glPDaiU3tfkErxyudrxlGOYXSps1AVZ+cfAMiwcyg776,iv:F5N1Z7oPWIQtsMzpJXEPeiHLn9t0i3HQiJeEV9b/xLg=,tag:BI9PyRdu6fIWRLRR22AdmQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWm9Gd3VJRnl4WlNmUTFR
            Rlh4cGxyQnJkb2lPNkRtd0o1bGpySVZ0eFFZCnBiMmhWang2WGNWeHdVbHBDY0or
            a0Q2ZFFJSkYvSnFQZ0xYRmxKbmNsd3cKLS0tIEhtbzVKd1hTd1ZGd1RPTXc4RzhL
            a3RwcWMrUVFJczVNMEwrUDlTRFRhOG8KTGww2gaYq6WIl0mRqnTVz7n5l0zhASga
            E9DBrveRwZr3M7Jn8/piS2qZGafZNApuxPff8Pg3fnu5O1Z0LoLLmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T20:45:14Z"
    mac: ENC[AES256_GCM,data:pbyOJKn95Q/bN3v+65PLcQPtsmakQR/3iYmCxtLxXLlmzkM0iz+6rV+8ODHHj9myY/pAr06fWeq0iapjie51Lek2HIxJnXYCEV3r91UERr8qIDvrL9UnMvX3OANXVXgswkMmStAcx2Z7x3YfqZJHtEThWp/7HXRMbu/Qf8DoRpM=,iv:S0O7qpVRZXelCud/MGoY5uEXdkl6HBlA0FhhEsDpUM4=,tag:xhYddCd0ii8pRN4Sx7s1OA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
