apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PZvhfZuxi1g7CMMWE19m+H52qxyR3l/2JO7/45eu0qmW0fEY5wuJP4o9sIx1XKQrh7RZsTj5yBzY4udz7g8x++r/apxAZpteqbihHM2eOsl73iu6WiFHkjCg6wm9j0T4wzaT0zJHNM6KSJcRmu5EGFH+7X30kx6++rPSe8UyIwEmC4RrUjYwwoXqPbtenWoNZdeYbw1sV0/xGdwrKRCUcBgAdZl5XOeIph3ZkgzAU4cBu+Y3yCNbcy/+vEw83W1g94ZIH9yWiZNfBvmPs/nJyXqwtPmmaCk10HP/KO5xDuKMhBKaeqKEhlJ77tXtgB5JFl82kYEF43GIOICM1UXqJ1QbIv7ts7D4HUqTHR494vR2mzPya2/rABP92CSRC4Xp,iv:G9A1wwau4SceEsmjG3i94y3JmUGJTzVqoTeGz8XWu5w=,tag:JxtZSDznluMn6YLnVCOHKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:BGML2FtYwDTrO5HKJPwtxCSthAxpb7DkQJQJnEoFyzoRRhlJjoD/PUD0XIrlYm3rWJgl4o/bteDimnuKTUzGriuYu1Y9C3kXKpq8N+zp/vkzLhNpHjP3fTAh3fn84XGdbbxA/V97TKm47K7RtctWt/s9MZ8ojx1TXYAIy7JiD5u0b73kdwI86N3s5sIyf2Wp5qb6LuJtf0aoprykAacS190e55mO3NxDRFCRJ4fUIBhqh+ZdxVvTEgyWj2SMEh14VVRe1ogtE471TzkCMg==,iv:zmAu3YHDyBxJzK1CMkeJBYIHQ3JJpcHl5g0ON0mPaRc=,tag:PlhvM0az8rxRZe7m9u2Clw==,type:str]
    known_hosts: ENC[AES256_GCM,data:zMyx6rXfLgeNvWtnpNsG4xBBF42K8RkUhHc/rMhtRnTMZ4Kq1/V8ckbKmvnzQoByFKTjEitbDsnsTdkGGB3zDCKMg5IHeeAnEoVokOOuv7cSm4qdoDzBM+c79p7ER5tUcyLw/2lnEsWR6moeZeSU5PzZAcbLyHk7eSWfXwnAvzQUOgIp+Tqi1EfPf+XzUaT+D1AL6G+DmgJQp3e2Rszs9MYbfMpmzPYsvERB,iv:EbPUFx+pu3akl4wWQOpF1/9VJeyFfR5ZXxI/muUcG+4=,tag:+cKiY8YuuWAHGv7Pehnmfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVndSTGh6UC9nOWhtSFVi
            MnA3OVhldGNvSjM0UnJmSE1DWXZjTWZhUWdzCno3aVJua1ZGVW1Ob0JUUHNtSXEw
            cXNzZkdBQlN1VHFSNklXUUpXRHIvOUEKLS0tIForZXFzOWZ3WDRTOC9DOFRwelhC
            S2Z1S2dVNWh5Q0pIdktvekVmVkJEbTQK/5qefJWPzUJ0KSxSxIondm8br8nay2m/
            2nJoM92PXjNgz/GoU3MaPFCIZVPjuyDrn6cvwJ8rH2C+PMhRlJB9KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T20:00:50Z"
    mac: ENC[AES256_GCM,data:x0hyTS/5tFsIdh/6LWXsrPFQMBpjoxMH7fZsVoCRPtsD3mjdJTiPNqTD2OM/wjQ5s9xdopdhbiGWubo5uo7Dgi1enLw40+D9GatTOFalECpTkr3bLB/jP/mVpUvZ8Zu1+xp5TrCyAdASLTVI5LP6UPPZMTbmODnEcKpniRQwVF4=,iv:PC6cfXpioMxB1QK7OEqZcQSiFT7TGfjoH556DHIaTEQ=,tag:y5Yt+i0EzbonbbCak8ceRw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
