apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uBOpx+P7O+5cAGJq5nH54Z8NxxVnWA4Vn/OB0rhomr9rqWsP6V6RVa+ahFXGrXxu9b7O1WHRMbxeGm6z0FXOzt5iBXNpMk62fYLgdebENzv3WEECiZd8ZEZEHD1vbXenhJLlU4SlgOnT5SPlBhHk/euToAl2SvBmfryLX2ldi4r3DCQEGJTUlg+0c5YUcTe3uTdnT6MXgbpNH9o6xTfuRsYZ5lFkQe9N3Swe4hi7RYCy0A3BjgPp3hM4j04Y2ejkZbMBRwtIa3hNCUAyFH9Lej9a2ATGZBR11edZUsn6yW0fDBj9atNVpogAhZCcyULo7HLBCpEVWCPlGPQ1sZErhu00+3rz7r0Ui764IEnaeoW2Lmh9huz6VEawGIixUGYC,iv:ObAkOtYgWU1VkqbgD5J6pwvaWA/C8GIW/Gz71af099k=,tag:UYzesL/U2ppIr6t6n/fW/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:QECaIbz9fGz1ap8q1jcC9sdREKKWsjcvh65I8tN3CEjaLpmO64EMMRAUlVP8QyEE+btd0WUaNYLl7dZKYU3OASjTw7FD1dyDmcDAO1TiRL1U2oG2F9VBnraQjTIcfd+LfciaG3bLxlGN8iNrcYguO+USHQLQb6QDHCFLa3ZLIexsmR1Tph4vUlMJU0yLYyGosBpmaWA4rgSGW4AS1oTSzEMaAvhc/vu7Mld+DOJnbL3Zsb6d5nQTaCU6kq5npKoeDM1Tr66+cdFdq7/ncA==,iv:88y3jMOMX2DT4kEp9+V6PiqMIV4fVq/ti9BqwXUWnS4=,tag:qsWiGBAnDaGkNTlflYdEbw==,type:str]
    known_hosts: ENC[AES256_GCM,data:VNcCa4mNnPt6qEsHcRtE8JoIAlZsfjAIBCzaPBVbaBdqFA5d0OAMObLakH2TfSdbkJTydY+YwwLKoxQjJBckuImtswRIsT9dDdsX4o9a7ptMLptYCL7vLb0Rie3VtAPKSL8ZRxje0I3JoYKmLT/w2XGlBvPkcQZmd3CHmpUtWFwvIWJtXC1S19oMpg0+B7Ncg77OD+EUdafrI/FL6j7nkqBUh3feBsT6d9tI,iv:HLVILlU402hrAK7fXIim50McrNDuw5SH+ju5SItG42E=,tag:aB0JeHhcXMnLrfb/7MCkjQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN1dhS2tvN0J0WXBnbE9U
            Z0xpSUdTWC9wTW9MekpLN0VncUhlQmlnYXpRCnRWM051ai9GbDl1ayt3OGFRZGd4
            MWJ1QWtEQ3FrcGtGdlBPSTV2OUg1Z00KLS0tIDMrczVNMENlRWJiRHZNQksrQldP
            aTdrMUpKMFNDVVMzVUZHbzR5eHdXSWcK/7/crPVt2Npvki4sq6/yNiqkVuPgVuYV
            +XRLHToPMBa7vgxF1LJjEDAyYJ0oSclv/o+jcrO+NUd9uyWFCfW/Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T22:58:35Z"
    mac: ENC[AES256_GCM,data:p/qKxnoUSp0n3+YlgtJj6AdcHSFo7TCYY+zppJ1qEnlY8GlGveur41rzMAHBXEBrGtN1WkuRYzhy4FTKEq+3MTN56q51A2O/krSyPi9UZ0v7EuG0fn4PTx0x+LzGE70lbarfgDSTfjD74J7Dl4aiN5B62nj3Y6xiP/xr9jfXufA=,iv:W2KZYuUdgFRMXZwWQ1VsWpIc+CQeHt6ZyQA5FNZVBnc=,tag:3r9aotS48ewjw66hAlJKsg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
