apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aIPML47Z7Pyed8mUixFEJ/PF/psQAD5CjLmaNo+O4630X/ShHYcvMN6PX8rkK+wjBp4qdzzXLX6DZO0smEFkUH/QNDNr4raYs9hxidZ6Kw0+R12JE28U+BVekXW2F6TqAAnGVYUuKFU9/j6PKWOw3VZOtT6tpkMoSsar2MRBjt8mCqnjEiEs7qlrfwepud6FNyUsuNYJS/D5E1v9zwvV7TEusqwxm3y4KBchnt+6jjrjkdK4FQzl5kDp8UCoYjoKJm45+tsVLXWnG7PYoMuP7ZdFRMIYKCaBzvLIpCE8tarLUrFNkGzkdmOlgHysiHxmzZHh8vapjA3LrKKPoHN3zJYgc18rat5vWiGFvxL00T9MUGTZro5COw5e/zG9XeQl,iv:qdhNpk0THOzr67xgqKH5a+G8AANW+4Gnk+7O2B3S8Ug=,tag:VU1c1FpLuVHp3ciw2DAIIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JqRufa6Y6KtXCRal6cI5tl7yPmlICP+3RAZ4/ZNG/CJzaNvolAT5H2nxvQEBFqBizQdkzBRrQL7m+sfw6OALYXiU0yBdJdfarvIEY3OOm0J5wA9TOFsnrFiDpZr5VDOKwANUmyJeOYTEPce06lrYTXdVnIPMolFYsADdUxyZN2IBY57RXkjgFzRhuPhf4yNZuUdb39GdOc7BVlBfZdkk4+VGRLDk/mmnj9s9CXEQQhGKgXjIAjvGK6g+BgPql3GmuiJqxIbTRA5nDpZLkA==,iv:wBKBjx6jxd+TPGyleS7zlB/R59p+CoXe5ApX69BzCqc=,tag:odnprh71LJsu4fxbV9+VIg==,type:str]
    known_hosts: ENC[AES256_GCM,data:/GsvGfRUoPNWt8sp/CELDM9sc6reUXzZzBSnW51GS5oC9d0YxAGco8osEe1iSs8zL8hIsVeAueqLGRZoaFWz3EijWxE42yhQuzJbzO9Z5y4nGQ2iv9vT2NdO4Xfc0ILM0GFOz+iFc7tUqxESWk/H/iCRCDztoeVVyk4VPBbT4j37VeZbPtR02Z0MATE4oXPBVNKxo3S5Sk7+Cwnb7AourxX+HqMSDrC8waH9,iv:YLZtfMCH3DHw/2Mul7g033lRVSlK8W3TaWoFwqS7c2o=,tag:fVI0vZPDhytPbwsUumCXiQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaXI4MVhqc2VpRjZGTE1m
            RGlkd3lZMWhRSk5rTFZkZnUxRkMvYWtLTGhVCjZqaHZjc3pRamlaenZqWmpUeSs5
            WjhQZU00ZTBWSTI3V3RBNURZY2pxd1EKLS0tIHNDRkl1YmdUbXZKMzJwWG4zTUNz
            Q2VZMGt0MTZRcnV4bzN1cVlBRTRudEEKcTGdGq+aChac/sgRfusk1EjMX4+VVImm
            bE7itBp+C2a1DmZfse5j8+/M97V6KQRgpvZsfmk57Iv0Fw5TVXLVXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T00:14:03Z"
    mac: ENC[AES256_GCM,data:++VqUR4P5qtFkl9AM9ZlqCOyL7PDuOdbvyW4WuTlrquVSAQrAv9uOt9qdpWi9IFs0pNg2BJvm1mjlJOucsQ8hqs0ituZuBFe/1Z7hcPHrB0XqDnmpaFmoZPwQmi3vP+HhgquW4a2WqX1kfgiM8htPTw4VHChJOi7+7QiZVjkOsA=,iv:HvUJ4TzTPu8pwZw75HJjukjtqhB/POpV9kmhZBX9uro=,tag:uOqlD0bVOAFdOZf4XqkZnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
