apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZJQSomc6tDh1mRAJtH/22vOwZnn1IbJkIP0+02sgVGXakyot3GbzZddiX4+mJzTnRUe1KhNPKmeI0QO/1bxnzD5fBHnnc4KpNH6MoyEa6eBnINES4RP+G5N4ftbfWx1/27tZoR+WpuuQXk0C40DyHFmv1UtbY5Q/iQqpRvuGJl+s1xuY2nlgFloAnSRxzFE4h6Pdy4+iQ4PT8I+rlR4Gxxjf1ffj4o+lvUpxc68KZwA6IM/EQcCaXNomCXkTQ4SJ6Q1+lrpAYy5H1wHfoQHv6Q43jQ94UYefEYyAqYlw1BGLaZXs5KZCZORG1rOE8k4x+hJDg77RXVPnnx0bYDr18FPfinVy0LwlzXTh+n+n2wYZFJ9FwUonM5kM/3d5l4ve,iv:hM1c0yqsJk0Ov1GBtkiq+xcitMjtmq5JYxrLeN38tr8=,tag:Mm9Pnko1hea9XHzuoa2EjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:M6qcFElA6VBRVB4yViOTIIvFz/JzwK4GMPz+LYF8QioKTgkpAlmhPXU66xuAOJ1nLu8lEi4KzxnxE/4I4VNdVOmQegG28LpY+CLJ+ZQlsmhUYMCVouJ40SznyHR/l2dpBENXWmKxZXbY7zO1Q8qo1FVoYO8O54cn1RCy91MOjHc21FGOEpm5j7ghBr+iQK3Y/YSqaA+V7x0jljvWmYayub5e7IHTdsFS24P40Fw63JRKhwffXBswrsLQcglQzXYPWNijXaRe6OQftIpGDg==,iv:xI+bKT3xdNks9Xji0ZJ7X2ReDna4vafQRZ5VqKkUZYk=,tag:zsxCixtgL/73CKz+qJe4Mw==,type:str]
    known_hosts: ENC[AES256_GCM,data:A0pO4G8blxg5rrZslZ4ocKWTKiJMK1CmDyYkGqJ7aRkfQ2+wIgjSNxeNsLtjfZCDNhqWzqV57VKwv6v4pSr9GAX6BxgzsRSTefyQCokTaSIgxheLSBYFJYAMQSVrPxnWH0A6a9ULCbxmfrZbKm6puY3bzNVvc9z/fuVCjSTyIK7h4+VgmLP3EvdK0vFUNrYGKm4c4U6xxOn4OmBd+u1Hl4hlEY+8bZXVhy92,iv:Hdzxxc8mAzUPUVVOfdw6x9d2J//aNWFBshQIZ9oHKps=,tag:SNmoUjbk4zyoFP6ZUTdL5Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcGRPb3lrWllhYzZaSWtM
            R1M0eXlpTWxablRiNkQrVExLbVM3NkxGRlI4Ck8ycmVnOG9UVWUxbFZrakVOcUhm
            dmhoejNMTlN0dGlPOU1XcDNBZU9PSmMKLS0tIGNTWUFnNWtoR2dwL2hsZkpTYUtV
            UEZqWjJLSlQ3VTNqTmpBc1N6Zzc2aE0K/YhRag4umnSni4WDxTTdeDi4uhNrKai9
            j9Da6X1Fvph1iJpbGSjl4IftF/e4avGgjTkEDWT1c0kOUvfwfPeqaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T04:24:53Z"
    mac: ENC[AES256_GCM,data:UGSIkCIYlskey/S1ri1Bn/O4CCA2GmATPg7OCO66J93dY8cYDwBNttPk8jZ8rQe0JoZCeCRTwiH0B2VOSOH7P6Q/pfut7EZlUX/Bi7nOMt7C4a8K9CaK7QOy05YZqKeW593seksySzV/FCcDo8izjGvLbGT1E6aQvh2ZCiGyy/c=,iv:RQGSkhxyqQS8oSS9l8QkMqzQqxC7iPNc7KesWeNGFyQ=,tag:aGbuftbktXmzT6SKkdmjog==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
