apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cwO760WSsCxOy7BljNTfiOKyfFsevUsLIT9dGfaQxAK/mSgrO+DOk26nLYXStX79VdhO50CuQfygpJu1BPiUUdfcibcuMg16bloPrvFKeYJPxTi+GniO7yyonEOCbc7pdaHaM77vFRGOHleAXF44aKmX93CynqyjZtnTMIw7KS/nU3IB8b4DfcMyLBqYTKgkNGTpabxFa9MDgz8gOlf4onvbv4qTjgU3l0IWHsWLaS9P+n/ZOcaHrMkeCu05XiXTvcToo3pHal/Lavd+J4Z7Rz2I0GZtN86yziMHyVR+nZWko9pygzllQBHyVjkVRpSazIL2X4I34u+znzg6+dOX9XRGkgbSwK8xU88NQjp/rOgj3MYdzFK+2iwa+SgwetBt,iv:frYuoX32xrIbT0nr24vQecAiBQbS+mhIYkE36U3ox7s=,tag:clRX+JECsLlOGQp1jUsX3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Bm2sCkuG5x6Kmc2IzAlJ1CQDAsUMAf2flz8hr5/xph3yafcXITxlQ9CoqtUhadaglwx69wCWUn3+xVA43DyMOWuwj3O2VsQE8QAExl5xZzkCakxdWv97dDWhqq03/NFjODFVZ9udrl3XOzrC/7d09kuitU+jmv+jw5qX/NShcJyrRzta7ag34S7LXNEsHGuqW8QyEEjYlpf4NM8XgkPu39uXKFMSVHDNdscFf6JWGngD7f4/bf6So80Cvl/XXTBDpq3FqPklDooKxrSnyA==,iv:jgeGNILmAG8zIHpRQsVWZcKSRS7qG42Nn5iNBHR0CVY=,tag:dyhJ3KPwO8zBc4LofxVKsA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Sq3Q94qlNxXbuohJjvJyNYtRTHlhy8ZTbEELTOSdx3NTFfrKVUnUFIo/NbT8iDjcyfA+NQMWPXHqH9jW8GVzQz2vR4Fxh9S37khokxCI2aJo9aF5U9XCxGbKk3ZKu61qW6sxS3pricVhVW4rKvAknX7JmA5wtXELmAjCL+LHegp9Xp7//wRsSaQkrMz4d442UAKz4KtTsEHDf40/o4gwNP5XtdYKW1IqAO6T,iv:CrMsgHVzn6tN1EClqP1Ac1PfzLLLvZiQi1iUIwDDyEs=,tag:AO7hbK+jxU4Izpk2byM3yg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYVVKN3d3MVlqd1d5YmN2
            b0k0YWxISTdHWks1TkhyQWt1N2NCZ2swbWlrCk90M29uZ1ArTjNEQldhcElJRGRH
            bTh0NXlLdlovbERGZzFYOFFXUXUveEkKLS0tIDVJNlA5ckFJR1VGNFNhTU9LdndS
            TVFjblVaTXFsVkVLRU1COTE1eE40ejQKDtgzkGwKQjlCUFJDtIQAaQbtQSBUqhQZ
            cTXzjJyj51bp70xMmRYtPZh0MfaosAPRSLSn5vb6HSIcqGVC+OPkRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T17:29:58Z"
    mac: ENC[AES256_GCM,data:W+rEjtWBvUt1ojnNQu2bNVY8qJ4l74QJ9c2Y4UpJksGV0+ImcC/rKIzOXhywMkyMTf3SLMDurNrl8Hepwjx7Z14h5wz3Bygide486Ng1swTtcG+WyLlqAWKuLrRkSA0vHKZ6WvW95eyeYOHzNmdYMoQeM7MKjS09jTHCN6YaI/o=,iv:7Saa5v7hb1m/8FsrALpxpQ7HYVTnY1SvoXNNsnJ/azc=,tag:8/yfzJ62ASzoE9qK4YuB5A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
