apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4h65mg/v3GPO8EihgHc/H0J/8I3lfvpKFlKP3iYI7+NRyRDopfzZT6PfcXvF//AcXuMUUcd41aCWtRLk6gbNQr5qoVm0l2KZnte4pgzE0dHlWtZzNIRCzxVrcAmudldiSMXfSun2jwEU3xHySdJ9g9tcKOley2RinUyI78NhEhrwv2Eh0BSv6Fas4QsFgihTVhX9cE1qJiuKuVm5cfPKcIYjJ7suQ1hVHVCBypk+HyT/PPoKNuQQUDcwiMus+dmx3CXvVVWQF802OFYiVOzbGcyVgQow55rFVW0Kp/BhWY8rUgl0bKGtUoEAUIDNYaGzMRB2CyWoUCqz3X2NTS7t3HLJbOZSuyLTYyLIAORC1cWXyMk9FCFIsvxw7gJdkcld,iv:rfgDGeOvspcTpEjF9kkkHeNHBXMPcAWEo7iKEIjCfUA=,tag:84qILOKZBIh8m9ebj6R3bQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:hTzAfUuP7HTxHjQkwjZBkzA03hqhFix717QvCFks05VL4vmqdgEwZ1xreD9EdZLfXYpHAhaVldTL+6w9eELh/ZkCeTF9ai3C48A6is/rfpe7XnI0Kj28iXqZNqVrzb25fw42vWN/ujJ6EzouuxDuidbR7jBl4+7vezEQvMv4MfAs81PRK/tpGrXad4tqp3EC/R0N1JM46msH5WDvuaDd9m8LAaQnTMyWi9qzqO5khRviIrxRfzC6He36MrXcHEqmNLvs5lXyYUpjdtMKww==,iv:dp6hu52CbJF+MTMUy/hUFVm2q4XXzYDXdBUYuyb++KI=,tag:qIZ6iD3icrMief0ZZRrHoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZlWyGuClYELo+orgjLZ6VE0KkpJMeAl/d+iBkHw2v3yht6QNXE+WuYayZcS3yQ7V4kgDVgsx8Shy2NdO4rx6NObiPkMk9ypjlDpzGKJFLSUgEpc2OOPUyUFwFm6piTjquOONWC1c8sy1frQHuGdloJC5r6+i561uwECrxtP3yAw9VkNuHoZTlNH8BSMkdT4MMeCHVuOWlIEhUbNhqbzWeyCOnGDU/ou3GJFm,iv:spbkShY/58I8aSM41WfFmMu5jLpkNJ7ohNDqE0/JCBM=,tag:lVhmIv2UCrnm3QGU/OYxIQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYXFEVjZHUk1UME5pOE1H
            WjM2VmJhV1VYeWg0V0xyU1VydVlmV0RoRHpFCkYwTGpYL3oxcGpuZVFMYXNLdUNn
            UUhxcUsraitNMStxSGJaWjNiK0ZYUW8KLS0tIDRkeFkweXBjQm4xdnVIMk5ZMGRS
            dmFra3hwVksweU5aN0pvTUNDa3hLdUUKgrTm6rq/6Ub4HwceOAfdkcBpzmRfe58u
            WyrOp/8Nv8axtPxL5kxWHHfFJkJWUkN+abfa3mlC1qzlMbOzcoCg3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T17:26:16Z"
    mac: ENC[AES256_GCM,data:LXi0G1yGZCIlWoPJaxqb2xli0wZny9P++P+nBhbqd06PkQWdBoYp7pxlHsK9ExvpTGX2PNBlXBWfOYZqj2Ydcc/A1qQOIzQxkBamjTcvOzsaHSYSnZD/RVkBy+BQbNln/8yApRmHa5anVRQoBLLPKoOdxCAhBbH+5ZHOX0I4M0g=,iv:thUOUmTxh7M5UvmFwKVQugMq9/L7SYb9f3l2C5Q+jgM=,tag:yg87bi6uBLYFpP9rR80ANw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
