apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SEE2is2CdyFbQ8tTtwxKS/wY3IDdGRNWy69lo/Otsyx03NX7OyYg9emtHoKHbcJTsVIADHtZeLfFPfkthSsBHzVoGj3CrpYgt0W3cO/vXv0GaN0zJEO298MqCPo6AuuDk4pAFl9ti+3qJ8r2q24FGUy5YiYGiBi82mECBONabLx827wKD8+0eyjs9mpWO62Is6CoPbEfAHDVmOaVRMCrlo/wS5kp0Oo2rIzNUorTgnxQPvcTmPRqXyx9qTnR2wIQcepEaPK1Un6bXw3TnaNGU2gZtr+bNYNSaMaOZtr9H3GQOZ9w2wDRiVoMEWoRoL1GqxbaSHg2CpLuwuwD6r6dR2WnU1KPXaqW6QgY/xSxtFuMtKY3Nh4QKKL/ApNs1YQB,iv:b+01HmIcM+fWUSWKn1uqh6k6c7O928UX915mGEBNjBo=,tag:GRrNtIK9TPff6yjL1ysKBA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Q5ivI172GSKtXJICbBbKkrMfrMiQ2CT655/FJE1bo7q1SMFhobQG63qQz83Hzjysn1FKKx0jdo+onNtN2R2EhRfp+dpSdox/KoSynyGWTkKIDE0Q0f5F4i3MUAJZhUWrW1eRh7GrZJiwagUqBbCg1SAQmLG02UuU01QT8xKEJOm5YDrfDFekCfyAvZYmhzylLPxvnLeB0NRm5VcoWTZhbUPrHvNJFs9cWcORacos59gI4p+VRz8Pj8goPrDe37uS932KhrBAgUa1WIo9MQ==,iv:YQSUZ+0f+97F8Co4bcoWk8POPD5EocsPTMaNFuWxyKA=,tag:IMjFWV/bJwRO4FNOvC/Z0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:sv0heAiGY2T9SwfhsZifxX+rj0BsZdF1qMM5RGzGRInGlVf3CEFsfnzr2ThfgLIpBvs/OjVMFD/4HWwv1sY2YmLA4/2EJrYgPsmz/XSxrbJyYbgarUVlsL/FVxUrRAhOqXPtT9NheOz/8KkVEIGAyE/c1ZqilROxz/wFOq9jKakN2oxQCFVx81AKnlxJGRfO9WdtHNtiVhgWoQ9xWb4wMNidnTKCm5aKSMw9,iv:aqdCfaGwThYrxOFc6hQq0GGTrMPgYuF+LTFJ5jyHgig=,tag:7IjiqJN+7isO1Ep4gk+QOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUVk0ZWl3SXN1eFVYZC9w
            MWY4RitVYkx3WEpmbCtnNDZxaVFWK2JrV1FnCitpdktlWUpuZnJJSzVKS2UxRHhv
            SnBKalFPTWliZXlsRW5OTTJJUlNsc1kKLS0tIDJMMnpwL3grN2lvaFIwMFZNWmlr
            cm1aWXAyWnVnbFFRNlFLZzh1dEM4Zm8KB5shSKfnw1Kiak8WgHRBFaVmIugMchJW
            J4SGJPKpHOoLFjaDZHI4ThA+D5Feu01v0rrSq7xci+IzUEwVVYtlmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T23:38:18Z"
    mac: ENC[AES256_GCM,data:qT1jGtNvzrxfjCOy1iczvdJzd3ug149E3CMaL2F3qpYqzM6sfB0m3cDoS5VtIO5ce4yMwTKvBT5pxpq52Sc6aaKR3/PZ7sJZzfhgUP8CrKZng7nQUDdxxLJ4RJiNI4N+6kZVHMwU+U78+dPKdzVgSVKgW0DHKPGzNrsmnyX4Efw=,iv:CktsMpieQCKLm430prDGZai/kD0DavMSRbJrbLhh1g0=,tag:R/O2quQUmoDqAi+fE9OlDQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
