apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8UOH3cBdGnw7GLbCtT26a53Ot0JE7IZtPeRunBVY+1TYnh4/yzUtve6HR1CD7ZvPV96Q6DRiV/Z05b1E9JIYDRTBig230mGZLSh7creid5dzN71AdDE6AtqkwPeVSZdnOWL2fxwso+pF/U0AfmBslKPWllUJR5YZSi8Gg1vJ8CZxkaYf2FCtdjFnT1jHpotl0ztlWc48SqS3gQPl5na8DGHMRdjH7o/Xz6WKe5w/LxyjpgsgYXlps/bmA8DGHW0ZwO8X6HvdVXaiXeBse2XHDeDj8GYWBODyQ+ZXmMN/Lq7zJ6fn+vtj3QMQtkJJrB809QZeZY+Vrbxo/TEph3xvu3as6i13JKqk+b2NmHA+B6BR+HYDYUhgLQIgsD2vqFBH,iv:5ZX9WHimSnwxUjfm/43h0K31EGgBAdHXQtgywh+n9cY=,tag:aDj1xMWNq2rKugzivZV/xg==,type:str]
    identity.pub: ENC[AES256_GCM,data:rZOG8s2GKZIYdkxxlm8sBmwEC+v99f10vIjwuzi50TYKqUQS0udljprmC/nh4e9/M6AG909dXXtiuA4rks89xKXUWOt8pt1pZVbGYhF7dP3aHCiYPSpz4SZhk6ZdeZBTUzIPn+UuwifRifXhDWIvyLzXcGsL11Hgxc+cW1B94SXBAZjAkGS1g9RYI6HMQud7xGY+U2FTsbGTxgvQh2ANJd531sKpRpnLhetw1scVs1XrIwUsyDrQdjo8J4aoSQJo90+rUfkVYlCiT/NYYg==,iv:+2EbxBh3vhmA0Y+jE1pBdPw9WWHdYTW9ZB5V7/BgTts=,tag:7EZgBwB68FJYj3g0jb/n6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:SSm9Bey2mTOvobhzcIcI1/jyYZhoeXJ/Jyv89PUWUNycN/PE0cRQUNdocdjJaIIDiycUhx5itow86HPEvNg8EmvIGhvP0ZNo5Ddr3lj+9VMSWvoVuZZUp3sgZQNmI/DtUMfd7HuidKxpypSXR39EuxC6W3DDU4gApFMXPd/CFU22wjolv//9kCfqa5on2tBsNt0X9w6ArpOnjsMu0vLruT4/eNxKh0D5qefV,iv:9i6CHSmjTcuTZi+xyQRjdTsqSTpcpC1418O6Spfrv8M=,tag:tHDl/fp/JGVp05uOEOuw5A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc2l3WDdISURtTitEb3dq
            Q0g4dndhUEE0TVh0SUc4Mi8yTHBDTUlPbW5BCkhkOG1ybnU5NE8wcjJta0VsNjU2
            RkVDRm9XUkxQZzNZK2R6L1IvelZvMzgKLS0tIGV4dVI0b2tzNndqeERLcEtCTHhQ
            UGdzVEtYbHBzK24reUZWZEdZYlNvYk0KTXo9MT+UXE1W2dVBADj3BGb5iwxCBtFC
            s18OYdlzs5AgnWTe26bA3pXAraMtsCr/f7AgXElYbcjWPz9XgU89fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:32:51Z"
    mac: ENC[AES256_GCM,data:ooRRfqvKtIAbZT1H3W+n+VBTLUMofMTsp9H6/7HqiygURHNmro3lavzugQnCHGBCT8n3dPWmaL9phE9YRui2oDwbqBM2RBpDRLcVOjuTfXrtF0UXzaq65dFNjvuHXfEg150pn15kEjKsnl1zalyQnnwA8JhEQIn+Bth4RIBfNjw=,iv:a9f013T3U3ncBer/iPFdRPD0nuqOSPnAnmDC3bc8qEo=,tag:JeTJhki44rldwUc84T9weg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
