apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beets-flask
  namespace: beets-flask
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.29.77
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Los_Angeles
    image:
      repository: ghcr.io/pspitzner/beets-flask
      tag: V1.2.1@sha256:98b8b87281e0526f3b9ee517ed1a75da76ae77bfc16564999c5e72d413d1ec50
      pullPolicy: IfNotPresent
    credentials:
      backblaze:
        type: s3
        url: "${S3_ENDPOINT_URL}"
        bucket: "${S3_BUCKET}-musicassistant"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
#        annotations:
#          nginx.ingress.kubernetes.io/enable-cors: "true"
#          nginx.ingress.kubernetes.io/cors-allow-origin: "https://jukebox.${DOMAIN_0}, https://${AUTH_ADDRESS}"
        hosts:
        - host: "beets.${DOMAIN_0}"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          nginx:
            enabled: true
#            auth:
#              type: "authentik"
#              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
#              externalHost: "jukebox.${DOMAIN_0}"
          traefik:
            enabled: false
        #      snapcast:
        #        enabled: true
        #        ingressClassName: external
        #        hosts:
        #        - host: snapcast.${DOMAIN_0}
        #          paths:
        #          - path: /
        #            pathType: Prefix

        #            overrideService:
        #              name: snapcast
        #              port: 1780

        #        integrations:
        #          certManager:
        #            enabled: true
        #            certificateIssuer: domain-0-le-prod
        #          nginx:
        #            enabled: true
        #            auth:
        #              type: "authentik"
        #              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
        #              externalHost: "snapcast.${DOMAIN_0}"
    service:
      main:
        enabled: true
        loadBalancerIP: ""
        ports:
          main:
            port: 5001
            targetPort: 5001
        type: LoadBalancer

    #      snapcast:
    #        enabled: true
    #        loadBalancerIP: ""
    #        ports:
    #          snapcast:
    #            enabled: true
    #            port: 1780
    #            targetPort: 1780
    #        type: LoadBalancer
    persistence:
      config:
        enabled: true
        mountPath: "/config"
        volsync:
        - name: config
          type: restic
          credentials: backblaze
          dest:
            #VolSync Destination (Restore)
            enabled: false
          src:
            #VolSync Source (Backup)
            enabled: false
      ingest:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media/audio/music/raw
        mountPath: /media/music/inbox
        server: ${NAS_IP}
      library:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media/audio/music/baked
        mountPath: /media/music/clean
        server: ${NAS_IP}
#    workload:
#      main:
#       podSpec:
#          containers:
#            main:
#              env:
#                USER_ID: 1000
#                GROUP_ID: 1000
    securityContext:
      container:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: false
